# -*- coding: utf-8 -*-
"""Builds plugins/nadlan-config/assets/arealife/place-icons.js: one icon per kind of place (the owner, 30.9: "a school is a
school icon, a restaurant is a restaurant icon"), shared by the area map (areamap.js, Mapbox) and the 3D world (world.js).
Glyphs: Lucide 1.49.0 (ISC licence, thin ink lines that match the house line icons), plus three drawn here in the same
24-unit grid and 2-unit stroke (the playground slide, the tooth, the Star of David for synagogues: every place of worship
in the project registries is a synagogue, checked 30.9).
  python build_place_icons.py <lucide-svg-dir>"""
import io, os, re, sys, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
SRC = sys.argv[1]
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "plugins", "nadlan-config", "assets", "arealife", "place-icons.js")

# kind -> glyph (kinds seen in the five place registries, 30.9)
KIND = {
    "school": "school", "kindergarten": "toy-brick", "daycare": "baby", "college": "graduation-cap", "university": "graduation-cap",
    "library": "library-big",
    "park": "trees", "garden": "tree-deciduous", "playground": "x-slide", "dog_park": "dog", "sport": "volleyball", "pitch": "volleyball",
    "sports_centre": "volleyball", "gym": "dumbbell", "fitness_centre": "dumbbell", "swimming_pool": "waves-ladder", "beach": "tree-palm",
    "bus_stop": "bus", "tram_stop": "tram-front", "subway_entrance": "train-front", "station": "train-front",
    "cafe": "coffee", "restaurant": "utensils", "fast_food": "sandwich", "bar": "wine", "pub": "beer", "bakery": "croissant",
    "ice_cream": "ice-cream-cone",
    "supermarket": "shopping-cart", "convenience": "shopping-cart", "greengrocer": "apple", "shopping": "shopping-bag", "mall": "store",
    "pharmacy": "pill", "chemist": "pill", "bank": "landmark", "atm": "banknote", "post_office": "mail",
    "health": "stethoscope", "clinic": "stethoscope", "doctors": "stethoscope", "hospital": "hospital", "dentist": "x-tooth",
    "optometrist": "glasses",
    "community": "users", "culture": "drama", "worship": "x-magen",
    # the square's own features in the 3D world (hamedina/world.json park_features, civic, the pond)
    "bike_path": "bike", "running_track": "footprints", "paths": "route", "pond": "waves", "kiosk": "coffee", "lawn": "tree-deciduous",
}
GROUP = {"education": "school", "outdoors": "trees", "transport": "bus", "food": "utensils", "essentials": "shopping-bag",
         "health": "stethoscope", "community": "users"}
CUSTOM = {
    "x-slide": '<path d="M5 21V8"/><path d="M9 21V8"/><path d="M5 8h4"/><path d="M5 12h4"/><path d="M5 16h4"/><path d="M9 8c4.5 0 5.5 12 11 12"/>',
    "x-tooth": '<path d="M7.5 3C5 3 3.5 5 3.5 7.3c0 2 .8 3.3 1.4 4.8.8 2 1 4.3 1.6 6.6.3 1.2 1 2.3 1.9 2.3 1.4 0 1.5-1.8 1.9-3.4.4-1.5.8-2.6 1.7-2.6s1.3 1.1 1.7 2.6c.4 1.6.5 3.4 1.9 3.4.9 0 1.6-1.1 1.9-2.3.6-2.3.8-4.6 1.6-6.6.6-1.5 1.4-2.8 1.4-4.8C20.5 5 19 3 16.5 3 14.8 3 13.6 4 12 4S9.2 3 7.5 3z"/>',
    "x-magen": '<path d="M12 2.8 20.2 17H3.8z"/><path d="M12 21.2 3.8 7h16.4z"/>',
}


def inner(name):
    if name in CUSTOM:
        return CUSTOM[name]
    s = open(os.path.join(SRC, name + ".svg"), encoding="utf-8").read()
    body = s[s.index(">", s.index("<svg")) + 1: s.rindex("</svg>")]
    body = re.sub(r"\s+", " ", body).replace(" />", "/>").replace("> <", "><").strip()
    return body


glyphs = {}
for n in sorted(set(KIND.values()) | set(GROUP.values())):
    glyphs[n] = inner(n)
js = """/* Place icons (design system v104.3, 30.9.2026): one icon per kind of place, shared by the area map (areamap.js) and the
 * 3D world (world.js). The owner, 30.9: "on maps I don't want to see dots ... a school is a school icon, a restaurant is a
 * restaurant icon". Generated by scripts/project-stage/build_place_icons.py - edit there, not here.
 * Glyphs: Lucide 1.49.0 (https://lucide.dev), ISC licence: Copyright (c) Lucide Icons and Contributors; permission to use,
 * copy, modify and distribute this software for any purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies. The slide, the tooth and the Star of David are drawn
 * for this site in the same grid. */
(function () {
  'use strict';
  var G = %s;
  var KIND = %s;
  var GROUP = %s;
  var COLOR = { education: '#3E5A45', outdoors: '#517048', transport: '#2F6F86', food: '#8A6B3F', essentials: '#9F6F54', health: '#A93F2A', community: '#6B4F7A', water: '#5F8793' };
  function glyph(k, g) { return KIND[k] || GROUP[g] || 'shopping-bag'; }
  function svg(k, g, stroke, sw) {
    return '<svg viewBox="0 0 24 24" fill="none" stroke="' + (stroke || 'currentColor') + '" stroke-width="' + (sw || 2) + '" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + G[glyph(k, g)] + '</svg>';
  }
  /* the map pin: a round badge in the group colour with the kind's glyph in white, a cream ring (48 px = 24 px at pixelRatio 2) */
  function pinSvg(k, g, size) {
    var s = size || 48, r = s / 2, gl = s * 0.5;
    return '<svg xmlns="http://www.w3.org/2000/svg" width="' + s + '" height="' + s + '" viewBox="0 0 ' + s + ' ' + s + '">'
      + '<circle cx="' + r + '" cy="' + r + '" r="' + (r - 2) + '" fill="' + (COLOR[g] || '#4A4740') + '" stroke="#FAF7F1" stroke-width="3"/>'
      + '<g transform="translate(' + (r - gl / 2) + ' ' + (r - gl / 2) + ') scale(' + (gl / 24) + ')" fill="none" stroke="#fff" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">' + G[glyph(k, g)] + '</g></svg>';
  }
  window.NLPlaceIcons = { glyph: glyph, svg: svg, pinSvg: pinSvg, COLOR: COLOR, KIND: KIND };
})();
""" % (json.dumps(glyphs, ensure_ascii=False, separators=(",", ":")), json.dumps(KIND, separators=(",", ":")), json.dumps(GROUP, separators=(",", ":")))
open(OUT, "w", encoding="utf-8", newline="\n").write(js)
print(OUT, len(js), "bytes,", len(glyphs), "glyphs,", len(KIND), "kinds")
