# -*- coding: utf-8 -*-
"""Generates scripts/project-stage/deploy372.py (release 1.72.372, HAD-376: the sight lines in the city layer's own frame) from
deploy371.py: the same safety chain (health, a token-gated one-run REST bridge, drift checks against the last deploy-result that
wrote each file, else 65af09be, never the branch HEAD, .bak372 backups, MD5-verified writes, page checks, automatic rollback, the
resilient record, the bridge always down), with no post written (the bridge's post list is empty), plus:

  the data: assets/project-stage/{rainbow,duo,dimri,ashira}/places.json with only their "sight" fields recomputed
            (build_places.py <project> --resight; sight_diff.py proves every other field identical), and
            assets/project-stage/rainbow/city.json with its frame declared ("origin", as the other three layers have it; the
            buildings, lots and every other byte the same);
  a check after the writes: each file as the site serves it at ?ver=1.72.372 is byte for byte the pinned file.

Every file is pinned by MD5 here: if any of them changes, the runner stops until this generator is run again.

  python scripts/project-stage/gen_deploy372.py
"""
import hashlib, io, json, os, re, subprocess, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
PLUG = os.path.join(REPO, "plugins", "nadlan-config")

SRC = io.open(os.path.join(HERE, "deploy371.py"), encoding="utf-8").read()
OUT = os.path.join(HERE, "deploy372.py")
V = "1.72.372"
FILES = ["assets/project-stage/rainbow/places.json", "assets/project-stage/duo/places.json", "assets/project-stage/dimri/places.json",
         "assets/project-stage/ashira/places.json", "assets/project-stage/rainbow/city.json"]


def md5(b):
    return hashlib.md5(b).hexdigest()


def must_replace(text, old, new, n=1, label=""):
    c = text.count(old)
    if c != n:
        raise SystemExit(f"FATAL generator: {label or old[:70]!r} x{c} (want {n})")
    return text.replace(old, new)


# ------------------------------------------------------------------------------------------------ what gets written, pinned
PIN = {}
for rel in FILES:
    b = open(os.path.join(PLUG, *rel.split("/")), "rb").read()
    d = json.loads(b.decode("utf-8"))                      # every file parses
    if rel.endswith("places.json") and not all("sight" in p for p in d["places"]):
        raise SystemExit(f"FATAL: {rel} has a place without sight lines")
    if rel.endswith("city.json") and not all(k in d.get("origin", {}) for k in ("lat", "lng", "grid_deg")):
        raise SystemExit(f"FATAL: {rel} declares no frame")
    PIN[rel] = md5(b)
# the sight-only proof, again at generation time: build_places.py --resight on the pinned files changes nothing
for pk in ("rainbow", "duo", "dimri", "ashira"):
    rel = f"assets/project-stage/{pk}/places.json"
    r = subprocess.run([sys.executable, os.path.join(HERE, "build_places.py"), pk, "--resight"], capture_output=True, text=True, encoding="utf-8")
    if r.returncode or md5(open(os.path.join(PLUG, *rel.split("/")), "rb").read()) != PIN[rel]:
        raise SystemExit(f"FATAL: build_places.py {pk} --resight does not reproduce the pinned {rel}: {r.stdout[-300:]}{r.stderr[-300:]}")
print("[gate] build_places.py --resight reproduces the four pinned places.json byte for byte")

t = SRC
# ------------------------------------------------------------------------------------------------ header and names
doc_end = t.index('"""', 3) + 3
t = '''"""Release 1.72.372 (HAD-376): the sight lines of the view from the floor and the 360 windows on Rainbow, DUO, Dimri Yama and
Ashira, computed in the city layer's own frame (the places and the landmarks turned with the grid, 10 and 11 degrees, like the
buildings they are compared with). GENERATED by gen_deploy372.py from deploy371.py; do not edit by hand: change the sources and
run the generator again (every file is pinned by MD5).

Writes: assets/project-stage/{rainbow,duo,dimri,ashira}/places.json (only the "sight" fields differ from what 1.72.361/365 wrote),
assets/project-stage/rainbow/city.json (its frame declared: one "origin" key added), nadlan-config.php (the version, on the live
text). No post, no meta, no new file. Rolls back on any failed check: the files from .bak372. The record deploy-result-372.json is
written as soon as the files are written.

  python scripts/project-stage/deploy372.py [--dry | --rollback]
"""''' + t[doc_end:]
t = must_replace(t, 'BAK = ".bak371"', 'BAK = ".bak372"')
t = must_replace(t, "NadLan-PS371/1.0", "NadLan-PS372/1.0")
t = must_replace(t, "NS = 'nadlan-ps371-'", "NS = 'nadlan-ps372-'")
t = must_replace(t, 'f"x-tmp-ps371-ops-{int(time.time())}"', 'f"x-tmp-ps372-ops-{int(time.time())}"')
# the bridge writes no post in this release
t = must_replace(t, "			// P9a (1.72.371): the Kikar Hamedina posts. Read: all five; written: ONLY the Hebrew post (content only); looked up by slug in any status (never a duplicate);",
                 "			// 1.72.372 (HAD-376): the Kikar Hamedina posts may be read; NONE is written (the list below is empty);")
t = must_replace(t, "			$kh_write = array( 'hamedina' ); // P9a: the Hebrew post's degrees as a word; the other four posts are not written",
                 "			$kh_write = array(); // 1.72.372 writes data files only")

# ------------------------------------------------------------------------------------------------ the checks: the same pages, at the new version
cs, ce = t.index("CHECKS = ["), t.index("H1_EXACTLY_ONE = [")
checks = t[cs:ce]
n_ver = checks.count("1.72.371")
checks = checks.replace("1.72.371", V)
for pk, bands in (("rainbow", None), ("dimri", "[10,25,36]"), ("ashira", "[10,22,32]"), ("duo", "[10,25,45]")):
    if f"assets/project-stage/{pk}/places.json?ver={V}" not in checks:
        raise SystemExit(f"FATAL generator: CHECKS has no line for {pk}/places.json")
t = t[:cs] + checks + t[ce:]
t = must_replace(t, 'print("[rollback] restoring .bak371 files")', 'print("[rollback] restoring .bak372 files")')

# ------------------------------------------------------------------------------------------------ main
ms = t.index("# ---------------------------------------------------------------- main")
MAIN = r'''# ---------------------------------------------------------------- main (1.72.372: HAD-376, the sight lines in the city layer's frame)
import signal  # noqa: E402

WANT_LIVE = "1.72.371"  # the checks name ?ver=1.72.372: this runner is for the release right after 1.72.371
PIN = __PIN__
NEWFILES = set()
FILES = __FILES__
RESULT = os.path.join(QA, "deploy-result-372.json")
NEW = {}
for rel in FILES:
    NEW[rel] = open(os.path.join(PLUG, *rel.split("/")), "rb").read()
    if md5(NEW[rel]) != PIN[rel]:
        raise SystemExit(f"FATAL: {rel} changed since gen_deploy372.py pinned it ({md5(NEW[rel])[:10]} != {PIN[rel][:10]}); run the generator again")
    json.loads(NEW[rel].decode("utf-8"))
HEAD = {rel: git_head("plugins/nadlan-config/" + rel) for rel in FILES}
os.makedirs(os.path.join(QA, "live-backup"), exist_ok=True)


def _stop(signum, frame):  # a stop from outside (the shell's timeout, a console break): the finally still runs
    raise KeyboardInterrupt(f"signal {signum}")


for _sg in ("SIGTERM", "SIGBREAK"):
    if hasattr(signal, _sg):
        try:
            signal.signal(getattr(signal, _sg), _stop)
        except Exception:
            pass


def sweep(when):
    """every temporary release bridge (x-tmp-*-ops-*) still on the site is switched off and deleted (bridge_sweep.py's rule)"""
    s, lst = snip("GET", "")
    rows = [x for x in (lst if s == 200 and isinstance(lst, list) else []) if re.match(r"x-tmp-[a-z0-9]+-ops-", str(x.get("name", ""))) and x.get("active")]
    if BR is not None:
        rows = [x for x in rows if x.get("id") != BR or when == "end"]
    for x in rows:
        a = snip("PUT", f"/{x['id']}/deactivate", {})[0]
        d = snip("DELETE", f"/{x['id']}", None)[0]
        print(f"[sweep {when}] active bridge {x['id']} {x['name']}: deactivate {a}, delete {d}")
    if not rows:
        print(f"[sweep {when}] no active temporary bridge left (http {s})")


REC = {}


def record(state, **extra):
    """deploy-result-372.json, written at once and then updated: a run stopped from outside never loses what it wrote.
    A rolled-back run keeps its record with an empty "files" (the next runner's drift check then looks further back)."""
    REC.update({"released": REC.get("released"), "from": REC.get("from"), "state": state, "at": time.strftime("%Y-%m-%d %H:%M:%S")})
    REC.update(extra)
    tmp = RESULT + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(REC, fh, ensure_ascii=False, indent=2)
    os.replace(tmp, RESULT)
    print(f"[record] {os.path.basename(RESULT)}: {state}")


def served_exact(tag):
    """each written file as the site serves it to a page (?ver=1.72.372), byte for byte the pinned file"""
    ok = True
    for rel in FILES:
        path = "/wp-content/plugins/nadlan-config/" + rel + "?ver=1.72.372&nlv=" + tag
        try:
            s, b = req("GET", path, raw=True, auth=False, timeout=90)
        except Exception as e:
            s, b = str(e)[:60], b""
        good = s == 200 and md5(b) == PIN[rel]
        print(f"[served] {'OK ' if good else 'BAD'} {s} {rel}: {md5(b)[:10] if b else '-'} (want {PIN[rel][:10]})")
        ok = ok and good
    return ok


def run_checks(tag):
    bad = verify_pages("ps372" + tag + str(int(time.time())))
    if not bad and not served_exact("ps372s" + tag + str(int(time.time()))):
        bad = ["served-files"]
    if not bad and not verify_order("ps372o" + tag + str(int(time.time()))):
        bad = ["order"]
    if not bad and not verify_home_order("ps372h" + tag + str(int(time.time()))):
        bad = ["home-order"]
    if not bad and not verify_kh("ps372k" + tag + str(int(time.time()))):
        bad = ["kikar-hamedina"]
    return bad


created = False
try:
    sweep("start")
    bridge_up()
    before = {}
    if "--rollback" in ARGS:
        rollback(True)
        wait_version(LIVE_VER)
        if os.path.exists(RESULT):
            REC.update(json.load(open(RESULT, encoding="utf-8")))
            REC["rolled_back_files"] = REC.get("files") or REC.get("rolled_back_files") or {}
            record("rolled back (--rollback)", files={})
        raise SystemExit(0)
    if LIVE_VER != WANT_LIVE:
        raise SystemExit(f"FATAL: live is {LIVE_VER}, this runner is for {WANT_LIVE} -> 1.72.372 (its checks name the version); regenerate it")

    LIVE = {}
    for rel in FILES:
        cur = live_get(rel)
        if cur.get("missing"):
            raise SystemExit("FATAL live file missing: " + rel)
        LIVE[rel] = base64.b64decode(cur["b64"])
        print(f"[drift] live {rel} {md5(LIVE[rel])[:10]} vs 65af09be {md5(HEAD[rel])[:10] if HEAD[rel] else '-'}")
        prev = None
        for n in range(371, 329, -1):  # the last release that wrote the file (a rolled-back record has no "files"); else 65af09be
            p = os.path.join(QA, f"deploy-result-{n}.json")
            if os.path.exists(p):
                prev = (json.load(open(p, encoding="utf-8")).get("files") or {}).get(rel)
                if prev:
                    print(f"        last written by 1.72.{n}: {prev[:10]}")
                    break
        if prev:
            if md5(LIVE[rel]) != prev:
                raise SystemExit(f"FATAL: live {rel} is not what the last release wrote; diff it before replacing it")
        elif HEAD[rel] is None or LIVE[rel].replace(CRLF, LF) != HEAD[rel].replace(CRLF, LF):
            raise SystemExit(f"FATAL: live {rel} differs from 65af09be; diff it before replacing it")
    cur_main = live_get("nadlan-config.php")
    live_main = base64.b64decode(cur_main["b64"])
    stamp = time.strftime("%Y%m%dT%H%M%S")
    if not DRY:
        for rel in FILES:
            open(os.path.join(QA, "live-backup", rel.replace("assets/project-stage/", "").replace("/", "-") + f".{stamp}.live"), "wb").write(LIVE[rel])
        open(os.path.join(QA, "live-backup", f"nadlan-config.php.{stamp}.live"), "wb").write(live_main)

    # the version bump, on the live text
    text = live_main.decode("utf-8")
    m = re.search(r"\* Version: (\d+)\.(\d+)\.(\d+)", text)
    old = ".".join(m.groups())
    new = f"{m.group(1)}.{m.group(2)}.{int(m.group(3)) + 1}"
    if new != "1.72.372":
        raise SystemExit(f"FATAL: the bump would be {old} -> {new}, not 1.72.372")
    for a, b2 in ((f" * Version: {old}", f" * Version: {new}"), (f"define( 'NADLAN_CONFIG_VERSION', '{old}' )", f"define( 'NADLAN_CONFIG_VERSION', '{new}' )")):
        n = text.count(a)
        if n != 1:
            raise SystemExit(f"FATAL anchor x{n} in nadlan-config.php: {a}")
        text = text.replace(a, b2)
    if text.count("'project-stage', 'together'") != 1 or text.count("'home-v3', 'pro-card', 'cta-sheet' ) as $nadlan_mod") != 1:
        raise SystemExit("FATAL: the live module list is not the 1.72.371 one")
    new_main = text.encode("utf-8")
    php_lint(new_main, "nadlan-config.php (live text, bumped)")
    print(f"[plan] {old} -> {new}; writing {len(FILES)} data files: {', '.join(FILES)}")
    print("[plan] no post, no meta, no new file")
    if DRY:
        print("[dry] no writes")
        raise SystemExit(0)

    REC.update({"released": new, "from": old, "live_before": dict({rel: md5(LIVE[rel]) for rel in FILES}, **{"nadlan-config.php": md5(live_main)})})
    FILES_MD5 = dict({rel: md5(NEW[rel]) for rel in FILES}, **{"nadlan-config.php": md5(new_main)})
    try:
        created = True
        for rel in FILES:
            put(rel, NEW[rel], expect=md5(LIVE[rel]))
        put("nadlan-config.php", new_main, expect=md5(live_main))
        record("written, checks pending", files=FILES_MD5)
    except BaseException as e:  # a write refused half way (drift, md5, a stop from outside): put everything back
        print("[FAIL] during writes:", e)
        rollback(created)
        if REC.get("released"):
            record("rolled back during the writes: " + str(e)[:200], files={}, rolled_back_files=FILES_MD5)
        raise
    print("[purge]", ops({"purge": 1}, "purge"))

    healthy = wait_version(new)
    bad = run_checks("a") if healthy else ["health"]
    after = speed("after") if healthy else {}
    if bad:
        print("[checks] first round:", bad, "- purge and look again")
        ops({"purge": 1}, "purge again")
        time.sleep(12)
        healthy = wait_version(new, 45)
        bad = run_checks("b") if healthy else ["health"]
    if bad:
        print("[FAIL] pages:", bad)
        rollback(created)
        wait_version(old, 60)
        record("rolled back after the checks: " + ", ".join(bad), files={}, rolled_back_files=FILES_MD5)
        raise SystemExit("ROLLED BACK")
    record("released and verified", files=FILES_MD5,
           checks="verify_pages + served_exact (the five files at ?ver=1.72.372, byte for byte) + verify_order + verify_home_order + verify_kh: OK")
    json.dump({"before": before, "after": after}, open(os.path.join(QA, "speed-372.json"), "w", encoding="utf-8"), indent=2)
    print("RELEASE 1.72.372 LIVE: the sight lines on /projects/rainbow-tel-aviv/, /projects/duo-tel-aviv/, /projects/dimri-yama-sde-dov/, /projects/ashira-sde-dov/")


finally:
    try:
        bridge_down()
    except BaseException as e:
        print("[bridge] down failed:", e)
    try:
        sweep("end")
    except BaseException as e:
        print("[sweep end] failed:", e)
'''
MAIN = MAIN.replace("__PIN__", json.dumps(PIN, indent=4)).replace("__FILES__", json.dumps(FILES))
t = t[:ms] + MAIN
io.open(OUT, "w", encoding="utf-8", newline="\n").write(t)
r = subprocess.run([sys.executable, "-m", "py_compile", OUT], capture_output=True, text=True)
if r.returncode:
    raise SystemExit("FATAL: deploy372.py does not compile: " + r.stderr)
# the bridge's PHP, linted (the placeholders filled)
bs = t.index("BRIDGE = r'''") + len("BRIDGE = r'''")
bridge_php = "<?php\n" + t[bs:t.index("'''", bs)].replace("__TOKEN__", "x" * 48).replace("__BAK__", ".bak372").replace("__NS__", "nadlan-ps372-xxxxxxxx")
tmp = os.path.join(os.environ.get("TEMP", "."), "bridge372-lint.php")
open(tmp, "w", encoding="utf-8").write(bridge_php)
r = subprocess.run(["php", "-l", tmp], capture_output=True, text=True)
os.unlink(tmp)
if r.returncode:
    raise SystemExit("FATAL: the bridge PHP does not lint: " + r.stdout + r.stderr)
left = [m.start() for m in re.finditer(r"1\.72\.371", t)]
print("wrote", OUT, "|", len(t), "chars | pinned", len(PIN), "files | bridge lint ok | py_compile ok | CHECKS moved to", V, f"({n_ver} names)",
      "| '1.72.371' named", len(left), "times (WANT_LIVE, history)")
for k, v in PIN.items():
    print(f"   {v}  {k}")
