# -*- coding: utf-8 -*-
"""Generates scripts/project-stage/deploy369.py (release 1.72.369, Kikar Hamedina P7: /projects/hamedina/ + /projects/hamedina-en/)
from deploy368.py: the same safety chain (health, a token-gated one-run REST bridge, drift checks against the last deploy-result
or 65af09be, never the branch HEAD, .bak369 backups, MD5-verified writes, page checks, automatic rollback), plus:

  - FILES: inc/project-stage.php as the LIVE base (65af09be) + the hunks of hamedina_ps_patch.py (NOT the branch file, which
    also carries the unreleased Batch 1/2), inc/wa-source.php (the facing on the source line), and the new files: the shared
    world module (assets/project-stage/world/world.js, world.css) and the Hamedina data and posters;
  - nadlan-config.php: the version bump on the LIVE text (as 368);
  - a NEW bridge op 'posts': create or update the two nadlan_project posts by slug (never a duplicate: looked up in any status
    first; more than one = stop), their content and every meta, each read back in the same request; 'posts_check' (read only:
    what exists, and any other project whose title names the towers); 'thumb' (the poster as the featured image, once);
    'posts_restore' (the rollback: a post that existed goes back to its saved status, title, content and meta; a post this run
    created goes to draft; nothing is ever deleted);
  - the page checks for both new pages (needs, nevers, H1 exactly one, one FAQPage, one BreadcrumbList, one map, the order).

Every file and both contents are pinned by MD5 here: if any of them changes, the runner stops until this generator is run
again. The runner is NOT run by the agent that prepares it (not even --dry: a dry run opens the bridge on the live site).

  python scripts/project-stage/gen_deploy369.py
"""
import hashlib, io, json, os, re, subprocess, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
PLUG = os.path.join(REPO, "plugins", "nadlan-config")
sys.path.insert(0, HERE)
import hamedina_ps_patch as KP  # noqa: E402
import hamedina_page_data as KD  # noqa: E402

SRC = io.open(os.path.join(HERE, "deploy368.py"), encoding="utf-8").read()
OUT = os.path.join(HERE, "deploy369.py")
NEWFILES = [
    "assets/project-stage/world/world.js",
    "assets/project-stage/world/world.css",
    "assets/project-stage/hamedina/world.json",
    "assets/project-stage/hamedina/places.json",
    "assets/project-stage/hamedina/poster-1600.jpg",
    "assets/project-stage/hamedina/poster-1600.webp",
    "assets/project-stage/hamedina/poster-800.jpg",
    "assets/project-stage/hamedina/poster-800.webp",
]
FILES = ["inc/project-stage.php", "inc/wa-source.php"] + NEWFILES


def md5(b):
    return hashlib.md5(b).hexdigest()


def must_replace(text, old, new, n=1, label=""):
    c = text.count(old)
    if c != n:
        raise SystemExit(f"FATAL generator: {label or old[:70]!r} x{c} (want {n})")
    return text.replace(old, new)


# ------------------------------------------------------------------------------------------------ what gets written, pinned
base = subprocess.run(["git", "-C", REPO, "show", f"{KP.BASE_COMMIT}:{KP.REL}"], capture_output=True).stdout.decode("utf-8")
release_ps = KP.apply(base, KP.BASE_COMMIT).encode("utf-8")
branch_ps = io.open(os.path.join(REPO, *KP.REL.split("/")), encoding="utf-8", newline="").read()
if not all(KP.carries(branch_ps).values()):
    raise SystemExit("FATAL: the branch's inc/project-stage.php does not carry every hunk (run hamedina_ps_patch.py --branch)")
PIN = {"inc/project-stage.php": md5(release_ps)}
for rel in FILES[1:]:
    PIN[rel] = md5(open(os.path.join(PLUG, *rel.split("/")), "rb").read())
CONTENT_PIN = {l: md5(KD.content(l).encode("utf-8")) for l in KD.POSTS}
for rel in ("inc/project-stage.php",):
    tmp = os.path.join(os.environ.get("TEMP", "."), "ps369-lint.php")
    open(tmp, "wb").write(release_ps)
    r = subprocess.run(["php", "-l", tmp], capture_output=True, text=True)
    os.unlink(tmp)
    if r.returncode:
        raise SystemExit("FATAL: the release copy does not lint: " + r.stdout + r.stderr)

t = SRC
# ------------------------------------------------------------------------------------------------ header and names
doc_end = t.index('"""', 3) + 3
t = '''"""Release 1.72.369 (P7 of the Kikar Hamedina loop, HAD-375): /projects/hamedina/ and /projects/hamedina-en/, the first project
pages on the SHARED world module (design system v104, KikarHamedinaWorld). GENERATED by gen_deploy369.py from deploy368.py; do
not edit by hand: change the sources and run the generator again (every file and both contents are pinned by MD5).

Writes: inc/project-stage.php (the LIVE base 65af09be + hamedina_ps_patch.py's hunks; the four stage projects render byte for
byte as before, see ps_identity_proof.py), inc/wa-source.php (the facing joins the floor on the WhatsApp source line), the world
module and the Hamedina data and posters (new files), nadlan-config.php (the version, on the live text); then the two
nadlan_project posts (created or updated by slug, never duplicated, every meta read back), the poster as their featured image.
Rolls back on any failed check: the files from .bak369, the new files removed, the posts to their saved state (a post this run
created goes to draft; nothing is deleted).

  python scripts/project-stage/deploy369.py [--dry | --rollback]
"""''' + t[doc_end:]
t = must_replace(t, 'BAK = ".bak368"', 'BAK = ".bak369"')
t = must_replace(t, "NadLan-PS368/1.0", "NadLan-PS369/1.0")
t = must_replace(t, "NS = 'nadlan-ps368-'", "NS = 'nadlan-ps369-'")
t = must_replace(t, 'f"x-tmp-ps368-ops-{int(time.time())}"', 'f"x-tmp-ps369-ops-{int(time.time())}"')

# ------------------------------------------------------------------------------------------------ the bridge: the posts ops
POSTS_OPS = r"""			// P7 (1.72.369): the two Kikar Hamedina posts. Only these two slugs; looked up by slug in any status (never a duplicate);
			// content and meta read back in the same request; a rollback restores the saved state and never deletes.
			$kh_slugs = array( 'hamedina', 'hamedina-en' );
			$kh_find  = function ( $slug ) {
				return get_posts( array( 'post_type' => 'nadlan_project', 'name' => $slug, 'post_status' => array( 'publish', 'draft', 'pending', 'private', 'future', 'trash' ), 'numberposts' => 5, 'fields' => 'ids', 'suppress_filters' => true ) );
			};
			$kh_state = function ( $pid, $keys ) {
				$po = get_post( $pid );
				$m  = array();
				foreach ( (array) $keys as $k ) { $m[ $k ] = metadata_exists( 'post', $pid, $k ) ? (string) get_post_meta( $pid, $k, true ) : null; }
				return array( 'id' => (int) $pid, 'status' => $po->post_status, 'title' => $po->post_title, 'content_b64' => base64_encode( (string) $po->post_content ), 'meta' => $m, 'thumb' => (int) get_post_thumbnail_id( $pid ) );
			};
			if ( ! empty( $b['posts_check'] ) ) {
				$res = array();
				foreach ( $kh_slugs as $slug ) {
					$f = $kh_find( $slug );
					$res[ $slug ] = array( 'ids' => array_map( 'intval', $f ), 'status' => $f ? get_post_status( (int) $f[0] ) : '' );
				}
				$other = array();
				foreach ( array( 'כיכר המדינה', 'Kikar Hamedina', 'Kikar HaMedina' ) as $s ) {
					foreach ( get_posts( array( 'post_type' => 'nadlan_project', 'post_status' => 'any', 's' => $s, 'numberposts' => 30, 'suppress_filters' => true ) ) as $po ) {
						$other[ $po->ID ] = array( 'id' => $po->ID, 'slug' => $po->post_name, 'status' => $po->post_status, 'title' => $po->post_title );
					}
				}
				$res['_title_matches'] = array_values( $other );
				$out['posts_check'] = $res;
			}
			if ( ! empty( $b['posts'] ) && is_array( $b['posts'] ) ) {
				$res = array();
				foreach ( $b['posts'] as $p ) {
					$slug = sanitize_title( (string) ( $p['slug'] ?? '' ) );
					if ( ! in_array( $slug, $kh_slugs, true ) ) { return new WP_Error( 'posts', 'slug not allowed: ' . $slug, array( 'status' => 400 ) ); }
					$content = base64_decode( (string) ( $p['content_b64'] ?? '' ), true );
					if ( false === $content || md5( $content ) !== (string) ( $p['content_md5'] ?? '' ) ) { return new WP_Error( 'posts', 'content md5 ' . $slug, array( 'status' => 400 ) ); }
					$found = $kh_find( $slug );
					if ( count( $found ) > 1 ) { return new WP_Error( 'posts', 'more than one post named ' . $slug, array( 'status' => 409 ) ); }
					$pid    = $found ? (int) $found[0] : 0;
					$before = $pid ? $kh_state( $pid, array_keys( (array) $p['meta'] ) ) : null;
					$arr    = array( 'post_type' => 'nadlan_project', 'post_status' => 'publish', 'post_name' => $slug, 'post_title' => (string) $p['title'], 'post_content' => $content, 'comment_status' => 'closed', 'ping_status' => 'closed' );
					if ( $pid ) { $arr['ID'] = $pid; }
					$kses = has_filter( 'content_save_pre', 'wp_filter_post_kses' );
					if ( $kses ) { kses_remove_filters(); } // the content is ours, exact (tables, classes, ids); read back below
					$r = $pid ? wp_update_post( wp_slash( $arr ), true ) : wp_insert_post( wp_slash( $arr ), true );
					if ( $kses ) { kses_init_filters(); }
					if ( is_wp_error( $r ) ) { return new WP_Error( 'posts', $slug . ': ' . $r->get_error_message(), array( 'status' => 500 ) ); }
					$pid = (int) $r;
					clean_post_cache( $pid );
					$meta = array();
					foreach ( (array) $p['meta'] as $k => $v ) {
						$k = (string) $k;
						if ( ! preg_match( '/^[A-Za-z0-9_\-]+$/', $k ) ) { $meta[ $k ] = 'refused'; continue; }
						update_post_meta( $pid, $k, wp_slash( (string) $v ) );
						$now = (string) get_post_meta( $pid, $k, true );
						// Yoast may keep "&" as "&amp;": the same text; anything else is a real mismatch (and the runner rolls back)
						$meta[ $k ] = ( $now === (string) $v || trim( html_entity_decode( $now, ENT_QUOTES, 'UTF-8' ) ) === trim( (string) $v ) ) ? 'ok' : 'MISMATCH: ' . substr( $now, 0, 80 );
					}
					$term = '';
					if ( ! empty( $p['city_term'] ) && taxonomy_exists( 'nadlan_city' ) ) {
						$tt = get_term_by( 'name', (string) $p['city_term'], 'nadlan_city' );
						if ( $tt ) { wp_set_object_terms( $pid, array( (int) $tt->term_id ), 'nadlan_city', false ); $term = (int) $tt->term_id; } else { $term = 'no such term (not created)'; }
					}
					if ( function_exists( 'YoastSEO' ) ) {
						try {
							$repo = YoastSEO()->classes->get( \Yoast\WP\SEO\Repositories\Indexable_Repository::class );
							$bld  = YoastSEO()->classes->get( \Yoast\WP\SEO\Builders\Indexable_Builder::class );
							$ix   = $repo->find_by_id_and_type( $pid, 'post', false );
							if ( $ix ) { $bld->build_for_id_and_type( $pid, 'post', $ix ); }
						} catch ( \Throwable $e ) { $meta['_yoast_indexable'] = 'error: ' . $e->getMessage(); }
					}
					do_action( 'litespeed_purge_post', $pid );
					$res[ $slug ] = array( 'id' => $pid, 'created' => $before ? 0 : 1, 'before' => $before, 'slug_now' => get_post_field( 'post_name', $pid ), 'status' => get_post_status( $pid ),
						'content_md5' => md5( (string) get_post_field( 'post_content', $pid, 'raw' ) ), 'meta' => $meta, 'city_term' => $term, 'link' => get_permalink( $pid ) );
				}
				$out['posts'] = $res;
			}
			if ( ! empty( $b['thumb'] ) && is_array( $b['thumb'] ) ) {
				$ids = array();
				foreach ( $kh_slugs as $slug ) { $f = $kh_find( $slug ); if ( $f ) { $ids[] = (int) $f[0]; } }
				$att = 0;
				foreach ( $ids as $pid ) { $tt = (int) get_post_thumbnail_id( $pid ); if ( $tt ) { $att = $tt; break; } }
				$made = 0;
				if ( ! $att && $ids ) {
					$src = $root . $rel( $b['thumb']['file'] );
					if ( ! is_readable( $src ) ) { return new WP_Error( 'thumb', 'no poster file', array( 'status' => 400 ) ); }
					require_once ABSPATH . 'wp-admin/includes/image.php';
					$up = wp_upload_bits( sanitize_file_name( (string) $b['thumb']['name'] ), null, file_get_contents( $src ) );
					if ( ! empty( $up['error'] ) ) { return new WP_Error( 'thumb', (string) $up['error'], array( 'status' => 500 ) ); }
					$att = wp_insert_attachment( array( 'post_mime_type' => 'image/jpeg', 'post_title' => (string) $b['thumb']['title'], 'post_status' => 'inherit' ), $up['file'], $ids[0] );
					if ( is_wp_error( $att ) || ! $att ) { return new WP_Error( 'thumb', 'attachment', array( 'status' => 500 ) ); }
					wp_update_attachment_metadata( $att, wp_generate_attachment_metadata( $att, $up['file'] ) );
					update_post_meta( $att, '_wp_attachment_image_alt', wp_slash( (string) $b['thumb']['alt'] ) );
					$made = 1;
				}
				foreach ( $ids as $pid ) { if ( ! get_post_thumbnail_id( $pid ) && $att ) { set_post_thumbnail( $pid, $att ); } }
				$out['thumb'] = array( 'att' => (int) $att, 'made' => $made, 'posts' => $ids, 'url' => $att ? wp_get_attachment_url( $att ) : '' );
			}
			if ( ! empty( $b['posts_restore'] ) && is_array( $b['posts_restore'] ) ) {
				$res = array();
				foreach ( $b['posts_restore'] as $slug => $st ) {
					$slug = sanitize_title( (string) $slug );
					if ( ! in_array( $slug, $kh_slugs, true ) ) { continue; }
					$f = $kh_find( $slug );
					if ( ! $f ) { $res[ $slug ] = 'none'; continue; }
					$pid = (int) $f[0];
					if ( empty( $st['before'] ) ) { // created by the release: to draft, never deleted
						wp_update_post( array( 'ID' => $pid, 'post_status' => 'draft' ) );
						$res[ $slug ] = array( 'id' => $pid, 'status' => get_post_status( $pid ) );
						continue;
					}
					$bf   = $st['before'];
					$kses = has_filter( 'content_save_pre', 'wp_filter_post_kses' );
					if ( $kses ) { kses_remove_filters(); }
					wp_update_post( wp_slash( array( 'ID' => $pid, 'post_status' => (string) $bf['status'], 'post_title' => (string) $bf['title'], 'post_content' => (string) base64_decode( (string) $bf['content_b64'] ) ) ) );
					if ( $kses ) { kses_init_filters(); }
					foreach ( (array) $bf['meta'] as $k => $v ) {
						if ( ! preg_match( '/^[A-Za-z0-9_\-]+$/', (string) $k ) ) { continue; }
						if ( null === $v ) { delete_post_meta( $pid, (string) $k ); } else { update_post_meta( $pid, (string) $k, wp_slash( (string) $v ) ); }
					}
					if ( ! empty( $bf['thumb'] ) ) { set_post_thumbnail( $pid, (int) $bf['thumb'] ); } else { delete_post_thumbnail( $pid ); }
					clean_post_cache( $pid );
					$res[ $slug ] = array( 'id' => $pid, 'status' => get_post_status( $pid ), 'restored' => 1 );
				}
				$out['posts_restore'] = $res;
			}
"""
t = must_replace(t, "			if ( ! empty( $b['head'] ) ) {\n", POSTS_OPS + "			if ( ! empty( $b['head'] ) ) {\n")

# ------------------------------------------------------------------------------------------------ the checks
cs, ce = t.index("CHECKS = ["), t.index("H1_EXACTLY_ONE = [")
checks = t[cs:ce].replace("1.72.368", "1.72.369")
# a new published project raises the catalogue's total (the facets are cached, so 975 or 976 right after): the structure stays
checks = must_replace(checks, "'975</strong> פרויקטים בקטלוג: 942 מתחמי פינוי בינוי'", "'פרויקטים בקטלוג: 942 מתחמי פינוי בינוי'")
KH_NEVER = ["מגדל ובנייני בוטיק סביב גינה", "הפרויקטים המתוכננים ברובע", "living-25w-card", "mountRainbowStage", "project-stage/bridge.js",
            "rainbow/stage.js", 'id="nlps-tour"', 'class="nlps-steps"', 'id="nlps-view"', 'class="nlds-sample"', 'id="nadlan-stage-i18n"',
            'class="nlpt-h1"', 'class="screen-reader-text">מגדלי', "data-nlps-floor=",
            # the site's blacklist (tools/source_audit.py) and the language-dna words the fleet's shell does not print (scanned 30.9)
            "בהמתנה לחומרי היזם", "יחליף אותו עם קבלתו", "בבדיקה מול היזם", "יוצגו עם קבלת נתונים", "תוכנית תתווסף", "טרם התקבלו",
            "מחכים ליזם", "אין שרטוטים", "0 חדרים", "כיוון בבדיקה", "· בקרוב", "הדגמה", "נקודות חמות", "נקודה חמה", "הבניין הוא המפה",
            "מפה לחיצה", "אינטראקטיב", "ריחוף", "רספונסיבי", "מובייל", "פיילוט", "פרוטוטייפ", "הפלטפורמה", "החוויה הדיגיטלית", "סימולציה", "אטלס"]
KH_HTML_NEVER = ["Codex", "Lovable", '<link rel="modulepreload" href="https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js"']
V = "1.72.369"
kh_he_need = ['<h1 id="nl-project-page-title" class="nlps-h1">מגדלי כיכר המדינה, תל אביב <span class="nlps-h1__en" lang="en">Kikar Hamedina Towers</span></h1>',
              '<div class="nlps-page nlps-page--world" dir="rtl" lang="he">', 'id="nlps"', 'id="nlps-stage"', 'nlps-stage--world', 'm.mountWorld(host',
              'id="nadlan-ps-world"', 'id="nadlan-ps-world-css"', f'world\\/world.js?ver={V}', f'hamedina\\/world.json?ver={V}',  # inside data-cfg (JSON escapes "/")
              f'hamedina/poster-800.webp?ver={V}', f'hamedina/places.json?ver={V}', 'class="nlps-ssr-poster"',
              '<div class="nl-lead"><p', 'מגדלי כיכר המדינה (Kikar Hamedina Towers) קמים בלב כיכר המדינה',
              'data-nlps-ev="hero-wa"', '<span>ייעוץ חינם</span>', 'דירות למכירה במגדלים', 'סיור וירטואלי בכיכר', 'class="nlcta-wa"', '<b>ייעוץ חינם</b>',
              'class="nlpf"', 'class="nlprog"', 'class="nlpd"', 'דירות שנמכרו במגדלי כיכר המדינה, לפי קומה', 'id="nlpjx-map"',
              'id="nlws-facts"', 'id="nlws-prices"', 'id="nlws-sale"', 'id="nlws-when"', 'מתי מגדלי כיכר המדינה יאוכלסו?', 'id="nlws-timeline"',
              'id="nlws-faq"', '<h2>שאלות נפוצות</h2>', 'id="nadlan-ps-faq"', '"FAQPage"', '"BreadcrumbList"', '"ApartmentComplex"',
              'nadlan-project-article', 'class="nl-projnotice"', 'חברת בעלי הקרקע בכיכר המדינה',
              'hreflang="he" href="https://nad-lan.co.il/projects/hamedina/"', 'hreflang="en" href="https://nad-lan.co.il/projects/hamedina-en/"',
              'hreflang="x-default" href="https://nad-lan.co.il/projects/hamedina/"', 'מגדלי כיכר המדינה תל אביב: מחירים, עסקאות, מפה ותלת ממד</title>',
              'fc?" · "+fc:""']
kh_en_need = ['<h1 id="nl-project-page-title" class="nlps-h1">Kikar Hamedina Towers, Tel Aviv</h1>', 'nlps-page--world', 'nlps-stage--world',
              'm.mountWorld(host', '&quot;lang&quot;:&quot;en&quot;', 'Kikar Hamedina Towers (מגדלי כיכר המדינה) rise in the heart',
              '<span>Free advice</span>', 'Apartments for sale in the towers', 'Virtual tour of the square', 'Built by Electra and Ashtrom',
              'id="nlws-facts"', 'id="nlws-when"', 'When will Kikar Hamedina Towers be ready?', '<h2>Frequently asked questions</h2>',
              '"FAQPage"', '"inLanguage":"en"', '"BreadcrumbList"', 'nadlan-project-article', 'class="nl-projnotice"', 'Kikar Hamedina landowners',
              'hreflang="he" href="https://nad-lan.co.il/projects/hamedina/"', 'hreflang="en" href="https://nad-lan.co.il/projects/hamedina-en/"',
              '<title>Kikar Hamedina Towers Tel Aviv: Prices, Deals, Map', f'world\\/world.js?ver={V}']
kh_en_never = KH_NEVER + ['class="nlpd"', 'id="nadlan-ps-faq"', "בנייה: אלקטרה ואשטרום", "עובדות בקצרה", "רוצה להופיע כאן?"]
new_checks = [
    ("/projects/hamedina/", kh_he_need, KH_NEVER, KH_HTML_NEVER),
    ("/projects/hamedina-en/", kh_en_need, kh_en_never, KH_HTML_NEVER),
    (f"/wp-content/plugins/nadlan-config/assets/project-stage/world/world.js?ver={V}", ["export function mountWorld", "ring: { r: 138, b: 172, look: 352, lookP: 356 }", "const waHref = (what) =>", "opensOf(p)"], [], []),
    (f"/wp-content/plugins/nadlan-config/assets/project-stage/world/world.css?ver={V}", ["--nlw-wa: #0F7A63;", ".nlw a.nlw-btn--wa, .nlw a.nlw-btn--wa:visited"], [], []),
    (f"/wp-content/plugins/nadlan-config/assets/project-stage/hamedina/world.json?ver={V}", ['"towers":', '"park_features":'], [], []),
    (f"/wp-content/plugins/nadlan-config/assets/project-stage/hamedina/places.json?ver={V}", ['"places":[', '"iso":['], [], []),
    ("/glossary/?t369=1", ['id="nadlan-wa-source"', 'fc?" · "+fc:""', '(path.length<=45&&'], ['id="nlcta-sheet"'], []),
]
body = "".join("    (%r, %r, %r, %r),\n" % c for c in new_checks)
checks = checks.rstrip()
if not checks.endswith("]"):
    raise SystemExit("FATAL generator: CHECKS does not end with ]")
checks = checks[:-1] + body + "]\n"
t = t[:cs] + checks + t[ce:]
t = must_replace(t, 'H1_EXACTLY_ONE = ["/", RB,', 'H1_EXACTLY_ONE = ["/projects/hamedina/", "/projects/hamedina-en/", "/", RB,')

# the Kikar Hamedina pages' own order and counts (after verify_order)
KH_VERIFY = '''

KH_ORDER = {
    "/projects/hamedina/": ['<h1 id="nl-project-page-title" class="nlps-h1">', 'class="nl-lead"', 'nlps-hero__cta', 'id="nlps"', 'class="nlpf"', 'id="nlpjx-map"',
                            'class="nlpd"', 'id="nlws-facts"', 'id="nlws-prices"', 'id="nlws-sale"', 'id="nlws-when"', 'id="nlws-faq"', 'class="nl-projnotice"', 'nadlan-project-article'],
    "/projects/hamedina-en/": ['<h1 id="nl-project-page-title" class="nlps-h1">', 'class="nl-lead"', 'nlps-hero__cta', 'id="nlps"', 'class="nlpf"', 'id="nlpjx-map"',
                               'id="nlws-facts"', 'id="nlws-prices"', 'id="nlws-sale"', 'id="nlws-when"', 'id="nlws-faq"', 'class="nl-projnotice"', 'nadlan-project-article'],
}


def verify_kh(tag):
    """the new pages: the order (the lead first, the article last), and exactly one H1, one FAQPage, one BreadcrumbList, one map"""
    ok = True
    for path, order in KH_ORDER.items():
        s, html = page(path + "?nlv=" + tag)
        body = body_of(html)
        pos = [body.find(x) for x in order]
        counts = {"h1": body.count("<h1"), "FAQPage": html.count('"FAQPage"'), "BreadcrumbList": html.count('"BreadcrumbList"'), "map": body.count('id="nlpjx-map"')}
        good = s == 200 and all(p > -1 for p in pos) and pos == sorted(pos) and all(v == 1 for v in counts.values())
        print(f"[kh] {'OK ' if good else 'BAD'} {path} order={list(zip([o[:18] for o in order], pos))} counts={counts}")
        ok = ok and good
    return ok
'''
t = must_replace(t, "\n\n# exact markup, each once:", KH_VERIFY + "\n\n# exact markup, each once:")

# the rollback: files, new files, and the posts to their saved state
rs, re_ = t.index("def rollback(created_any):"), t.index("# ---------------------------------------------------------------- main")
t = t[:rs] + '''def rollback(created_any, posts_state=None):
    print("[rollback] restoring .bak369 files")
    for rel in ["nadlan-config.php"] + [r for r in FILES if r not in NEWFILES]:
        print("  ", rel, ops({"restore": rel}, "restore " + rel).get("restore"))
    for rel in sorted(NEWFILES):
        ops({"unlink": rel}, "unlink " + rel)
    print("   new files removed:", len(NEWFILES))
    if posts_state:
        print("[rollback] posts:", json.dumps(ops({"posts_restore": posts_state}, "posts restore").get("posts_restore"), ensure_ascii=False))
    ops({"purge": 1}, "purge")


''' + t[re_:]

# ------------------------------------------------------------------------------------------------ main
ms = t.index("# ---------------------------------------------------------------- main")
MAIN = '''# ---------------------------------------------------------------- main (1.72.369: Kikar Hamedina P7)
sys.path.insert(0, os.path.join(REPO, "scripts", "project-stage"))
import hamedina_ps_patch as KP  # noqa: E402  the hunks (the release copy of inc/project-stage.php = 65af09be + these)
import hamedina_page_data as KD  # noqa: E402  the two posts: content, SEO and meta

WANT_LIVE = "1.72.368"  # the checks name ?ver=1.72.369: this runner is for the release right after 1.72.368
PIN = __PIN__
CONTENT_PIN = __CONTENT_PIN__
NEWFILES = set(__NEWFILES__)
FILES = __FILES__
POSTS_BACKUP = os.path.join(QA, "posts-before-369.json")
NEW = {}
NEW["inc/project-stage.php"] = KP.apply(git_head(KP.REL).decode("utf-8"), "65af09be").encode("utf-8")  # git_head reads 65af09be
for rel in FILES[1:]:
    NEW[rel] = open(os.path.join(PLUG, *rel.split("/")), "rb").read()
for rel in FILES:
    if md5(NEW[rel]) != PIN[rel]:
        raise SystemExit(f"FATAL: {rel} changed since gen_deploy369.py pinned it ({md5(NEW[rel])[:10]} != {PIN[rel][:10]}); run the generator again")
if not all(KP.carries(open(os.path.join(PLUG, "inc", "project-stage.php"), encoding="utf-8").read()).values()):
    raise SystemExit("FATAL: the branch's inc/project-stage.php lacks the hunks the release writes")
for rel in FILES:
    if rel.endswith(".php"):
        php_lint(NEW[rel], rel)
POSTS = []
for lang in ("he", "en"):
    c = KD.content(lang).encode("utf-8")
    if md5(c) != CONTENT_PIN[lang]:
        raise SystemExit(f"FATAL: the {lang} content changed since it was pinned; run gen_deploy369.py again")
    POSTS.append({"slug": KD.POSTS[lang]["slug"], "title": KD.POSTS[lang]["title"], "content_b64": base64.b64encode(c).decode(), "content_md5": md5(c),
                  "meta": {k: (repr(v) if isinstance(v, float) else str(v)) for k, v in KD.meta(lang).items()}, "city_term": "תל אביב יפו" if lang == "he" else ""})
HEAD = {rel: git_head("plugins/nadlan-config/" + rel) for rel in FILES}
os.makedirs(os.path.join(QA, "live-backup"), exist_ok=True)


def restore_state():
    if os.path.exists(POSTS_BACKUP):
        d = json.load(open(POSTS_BACKUP, encoding="utf-8"))
        return {slug: {"before": v.get("before")} for slug, v in d.items()}
    return {"hamedina": {"before": None}, "hamedina-en": {"before": None}}


created = False
posts_state = None
try:
    s, lst = snip("GET", "")
    for x in (lst if s == 200 and isinstance(lst, list) else []):
        if re.match(r"x-tmp-(ps3[0-9][0-9]|bl24[45]|pl246|wa247|tc248|bv249|pe250|fg25[12]|bl253|lg254|ps25[5-9]|ps2[6-9][0-9]|had247)-ops-", str(x.get("name", ""))):
            print("[sweep] deactivating leftover bridge", x["id"], snip("PUT", f"/{x['id']}/deactivate", {})[0])
    bridge_up()
    before = {}
    if "--rollback" in ARGS:
        rollback(True, restore_state())
        wait_version(LIVE_VER)
        raise SystemExit(0)
    if LIVE_VER != WANT_LIVE:
        raise SystemExit(f"FATAL: live is {LIVE_VER}, this runner is for {WANT_LIVE} -> 1.72.369 (its checks name the version); regenerate it")

    # the posts, read only first: never a duplicate, never another project that already names the towers
    pc = ops({"posts_check": 1}, "posts check")["posts_check"]
    print("[posts] now:", json.dumps({k: v for k, v in pc.items() if not k.startswith("_")}, ensure_ascii=False))
    for slug in ("hamedina", "hamedina-en"):
        if len(pc[slug]["ids"]) > 1:
            raise SystemExit(f"FATAL: {len(pc[slug]['ids'])} posts named {slug}; clean up by hand first")
    ours = set(i for sl in ("hamedina", "hamedina-en") for i in pc[sl]["ids"])
    clash = [m for m in pc.get("_title_matches", []) if m["id"] not in ours and re.search(r"מגדלי כיכר המדינה|Kikar Ha[Mm]edina Towers", m["title"])]
    print("[posts] other projects whose title mentions the square:", json.dumps(pc.get("_title_matches", []), ensure_ascii=False)[:600])
    if clash:
        raise SystemExit("FATAL: another project post already names the towers: " + json.dumps(clash, ensure_ascii=False) + " (decide with the owner before a second page)")

    LIVE = {}
    for rel in FILES:
        cur = live_get(rel)
        if rel in NEWFILES:
            if not cur.get("missing"):
                raise SystemExit("FATAL new file already on the server: " + rel)
            LIVE[rel] = None
            print(f"[drift] {rel}: new file, not on the server yet (ok)")
            continue
        if cur.get("missing"):
            raise SystemExit("FATAL live file missing: " + rel)
        LIVE[rel] = base64.b64decode(cur["b64"])
        print(f"[drift] live {rel} {md5(LIVE[rel])[:10]} vs 65af09be {md5(HEAD[rel])[:10] if HEAD[rel] else '-'}")
        prev = None
        for n in range(368, 359, -1):  # the last release that wrote the file; else 65af09be (never the branch HEAD)
            p = os.path.join(QA, f"deploy-result-{n}.json")
            if os.path.exists(p):
                prev = json.load(open(p, encoding="utf-8"))["files"].get(rel)
                if prev:
                    print(f"        last written by 1.72.{n}: {prev[:10]}")
                    break
        if prev:
            if md5(LIVE[rel]) != prev:
                raise SystemExit(f"FATAL: live {rel} is not what the last release wrote; diff it before replacing it")
        elif HEAD[rel] is None or LIVE[rel].replace(CRLF, LF) != HEAD[rel].replace(CRLF, LF):
            raise SystemExit(f"FATAL: live {rel} differs from 65af09be; diff it before replacing it")
    cur_main = live_get("nadlan-config.php")
    live_main = base64.b64decode(cur_main["b64"])
    stamp = time.strftime("%Y%m%dT%H%M%S")
    if not DRY:
        for rel in FILES:
            if LIVE[rel] is not None and rel not in NEWFILES:
                open(os.path.join(QA, "live-backup", rel.split("/")[-1] + f".{stamp}.live"), "wb").write(LIVE[rel])
        open(os.path.join(QA, "live-backup", f"nadlan-config.php.{stamp}.live"), "wb").write(live_main)

    # the version bump, on the live text
    text = live_main.decode("utf-8")
    m = re.search(r"\\* Version: (\\d+)\\.(\\d+)\\.(\\d+)", text)
    old = ".".join(m.groups())
    new = f"{m.group(1)}.{m.group(2)}.{int(m.group(3)) + 1}"
    if new != "1.72.369":
        raise SystemExit(f"FATAL: the bump would be {old} -> {new}, not 1.72.369")
    for a, b2 in ((f" * Version: {old}", f" * Version: {new}"), (f"define( 'NADLAN_CONFIG_VERSION', '{old}' )", f"define( 'NADLAN_CONFIG_VERSION', '{new}' )")):
        n = text.count(a)
        if n != 1:
            raise SystemExit(f"FATAL anchor x{n} in nadlan-config.php: {a}")
        text = text.replace(a, b2)
    if text.count("'project-stage', 'together'") != 1 or text.count("'home-v3', 'pro-card', 'cta-sheet' ) as $nadlan_mod") != 1:
        raise SystemExit("FATAL: the live module list is not the 1.72.368 one")
    new_main = text.encode("utf-8")
    php_lint(new_main, "nadlan-config.php (live text, bumped)")
    print(f"[plan] {old} -> {new}; writing {len(FILES)} files ({len(NEWFILES)} new): {', '.join(FILES)}")
    print("[plan] posts:", ", ".join(f"{p['slug']} ({'update ' + str(pc[p['slug']]['ids'][0]) if pc[p['slug']]['ids'] else 'create'}, {len(p['meta'])} meta)" for p in POSTS))
    if DRY:
        print("[dry] no writes")
        raise SystemExit(0)

    try:
        created = True
        for rel in FILES:
            put(rel, NEW[rel], expect=("missing" if LIVE[rel] is None else md5(LIVE[rel])))
        put("nadlan-config.php", new_main, expect=md5(live_main))
        print("[purge]", ops({"purge": 1}, "purge"))
        # one post per request: each post's saved state is kept before the next one is touched (a rollback never loses one)
        pr = {}
        posts_state = {}
        for p in POSTS:
            pr[p["slug"]] = ops({"posts": [p]}, "post " + p["slug"])["posts"][p["slug"]]
            posts_state[p["slug"]] = {"before": pr[p["slug"]].get("before")}
            json.dump(pr, open(POSTS_BACKUP, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
        for p in POSTS:
            r = pr[p["slug"]]
            bad_meta = {k: v for k, v in r["meta"].items() if v != "ok"}
            print(f"[posts] {p['slug']}: id {r['id']} {'created' if r['created'] else 'updated'}, {r['status']}, slug {r['slug_now']}, content {'ok' if r['content_md5'] == p['content_md5'] else 'MISMATCH'}, meta ok {sum(1 for v in r['meta'].values() if v == 'ok')}/{len(p['meta'])}, city term {r['city_term']}, {r['link']}")
            if r["content_md5"] != p["content_md5"] or bad_meta or r["slug_now"] != p["slug"] or r["status"] != "publish":
                raise SystemExit(f"FATAL posts {p['slug']}: {json.dumps(bad_meta, ensure_ascii=False)[:300]}")
        try:
            th = ops({"thumb": {"file": "assets/project-stage/hamedina/poster-1600.jpg", "name": "kikar-hamedina-towers-tel-aviv.jpg",
                                "title": "מגדלי כיכר המדינה, תל אביב (הדמיה)", "alt": "הדמיה של מגדלי כיכר המדינה בתל אביב: שלושה מגדלים מסתובבים סביב הפארק והאגם"}}, "thumb")["thumb"]
            print("[thumb]", th)
        except SystemExit as e:  # the featured image is not a reason to roll back
            print("[thumb] not set:", e)
    except BaseException as e:  # a write refused half way (drift, lint, md5, a post): put everything back
        print("[FAIL] during writes:", e)
        rollback(created, posts_state or None)
        raise
    print("[purge]", ops({"purge": 1}, "purge"))

    healthy = wait_version(new)
    bad = verify_pages("ps369" + str(int(time.time()))) if healthy else ["health"]
    if healthy and not bad and not verify_order("ps369o" + str(int(time.time()))):
        bad = ["order"]
    if healthy and not bad and not verify_home_order("ps369h" + str(int(time.time()))):
        bad = ["home-order"]
    if healthy and not bad and not verify_kh("ps369k" + str(int(time.time()))):
        bad = ["kikar-hamedina"]
    after = speed("after") if healthy else {}
    if bad:
        ops({"purge": 1}, "purge again")
        time.sleep(12)
        healthy = wait_version(new, 45)
        bad = verify_pages("ps369b" + str(int(time.time()))) if healthy else ["health"]
        if healthy and not bad and not verify_order("ps369p" + str(int(time.time()))):
            bad = ["order"]
        if healthy and not bad and not verify_home_order("ps369q" + str(int(time.time()))):
            bad = ["home-order"]
        if healthy and not bad and not verify_kh("ps369r" + str(int(time.time()))):
            bad = ["kikar-hamedina"]
    if bad:
        print("[FAIL] pages:", bad)
        rollback(created, posts_state)
        wait_version(old, 60)
        raise SystemExit("ROLLED BACK")
    json.dump({"released": new, "from": old, "at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "files": dict({rel: md5(NEW[rel]) for rel in FILES}, **{"nadlan-config.php": md5(new_main)}),
        "live_before": dict({rel: (md5(LIVE[rel]) if LIVE[rel] is not None else "missing") for rel in FILES}, **{"nadlan-config.php": md5(live_main)}),
        "posts": {slug: {"id": v["id"], "created": v["created"], "link": v["link"]} for slug, v in json.load(open(POSTS_BACKUP, encoding="utf-8")).items()}},
        open(os.path.join(QA, "deploy-result-369.json"), "w", encoding="utf-8"), indent=2)
    json.dump({"before": before, "after": after}, open(os.path.join(QA, "speed-369.json"), "w", encoding="utf-8"), indent=2)
    print(f"RELEASE {new} LIVE: https://nad-lan.co.il/projects/hamedina/ and https://nad-lan.co.il/projects/hamedina-en/")


finally:
    bridge_down()
'''
MAIN = (MAIN.replace("__PIN__", json.dumps(PIN, indent=4).replace("\n", "\n"))
            .replace("__CONTENT_PIN__", json.dumps(CONTENT_PIN))
            .replace("__NEWFILES__", json.dumps(NEWFILES))
            .replace("__FILES__", json.dumps(FILES)))
t = t[:ms] + MAIN
io.open(OUT, "w", encoding="utf-8", newline="\n").write(t)
r = subprocess.run([sys.executable, "-m", "py_compile", OUT], capture_output=True, text=True)
if r.returncode:
    raise SystemExit("FATAL: deploy369.py does not compile: " + r.stderr)
# the bridge's PHP, linted (the placeholders filled)
bs = t.index("BRIDGE = r'''") + len("BRIDGE = r'''")
bridge_php = "<?php\n" + t[bs:t.index("'''", bs)].replace("__TOKEN__", "x" * 48).replace("__BAK__", ".bak369").replace("__NS__", "nadlan-ps369-xxxxxxxx")
tmp = os.path.join(os.environ.get("TEMP", "."), "bridge369-lint.php")
open(tmp, "w", encoding="utf-8").write(bridge_php)
r = subprocess.run(["php", "-l", tmp], capture_output=True, text=True)
os.unlink(tmp)
if r.returncode:
    raise SystemExit("FATAL: the bridge PHP does not lint: " + r.stdout + r.stderr)
print("wrote", OUT, "|", len(t), "chars | pinned", len(PIN), "files + 2 contents | bridge lint ok | py_compile ok")
for k, v in PIN.items():
    print(f"   {v}  {k}")
print("   contents:", CONTENT_PIN)
