# -*- coding: utf-8 -*-
"""Generates scripts/project-stage/deploy380.py (release 1.72.380, HAD-375, design v104.5: the rest of Codex's QA of 1.72.373/374)
from deploy379.py with the same safety chain, chained after P9c's 1.72.379 (WANT_LIVE 1.72.379). Replaced whole (drift-checked):
world/world.js, world/world.css, arealife/areamap.js. Edited on the LIVE text: inc/conversion-cta.php (the WhatsApp bar counts the
stage's inputs as controls: '#nlps input'). nadlan-config.php: the version. No new file, no post.

  python scripts/project-stage/gen_deploy380.py
"""
import hashlib, io, json, os, re, subprocess, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
PLUG = os.path.join(REPO, "plugins", "nadlan-config")

SRC = io.open(os.path.join(HERE, "deploy379.py"), encoding="utf-8").read()
OUT = os.path.join(HERE, "deploy380.py")
V = "1.72.380"
FILES = []
NEWF = []
PHP_EDITS = [
    ["inc/conversion-cta.php", "#nlps-view-cta button,#nlps-view-cta a')", "#nlps-view-cta button,#nlps-view-cta a,#nlps summary')"],
    ["inc/project-stage.php", "#nlps .nlw-compass button,#nlps .nlw-enter'", "#nlps .nlw-compass button,#nlps .nlw-enter,#nlps summary'"],
]


def md5(b):
    return hashlib.md5(b).hexdigest()


def must_replace(text, old, new, n=1, label=""):
    c = text.count(old)
    if c != n:
        raise SystemExit(f"FATAL generator: {label or old[:70]!r} x{c} (want {n})")
    return text.replace(old, new)


# ------------------------------------------------------------------------------------------------ what gets written, pinned
PIN = {}
for rel in FILES:
    b = open(os.path.join(PLUG, *rel.split("/")), "rb").read()
    if b"\r\n" in b:
        raise SystemExit(f"FATAL: {rel} has CRLF line ends")
    if rel.endswith(".js"):
        r = subprocess.run(["node", "--check", os.path.join(PLUG, *rel.split("/"))], capture_output=True, text=True)
        if r.returncode:
            raise SystemExit(f"FATAL: {rel} does not parse: {r.stderr[-400:]}")
    PIN[rel] = md5(b)
W = open(os.path.join(PLUG, "assets", "project-stage", "world", "world.js"), encoding="utf-8").read()
for must in ("cv.style.removeProperty('touch-action')", "function placeChrome()", "ui.waFull", "function gestureHint(kind)", "has-i", "FEAT_K", "exampleHtml()", "v104.4b", "v104.5", "gestureHint('wheel')", "const hp = coarse ? 7 : 0", "cardOpener"):
    if must not in W:
        raise SystemExit("FATAL: world.js lacks " + must)
A = open(os.path.join(PLUG, "assets", "arealife", "areamap.js"), encoding="utf-8").read()
for must in ("'icon-allow-overlap': false", "function iconId(p)", "'text-optional': false", "kindSvg(p)", "getRTLTextPluginStatus", "'text-field': ['get', 'name'], 'text-font':"):
    if must not in A:
        raise SystemExit("FATAL: areamap.js lacks " + must)
if "['concat', 'nlam-', ['get', 'g']]" in A or ".replace(/^<svg[^>]*>|<\\/svg>$/g, '')" in A:
    raise SystemExit("FATAL: areamap.js still has the old pin layer / the black-blob regex")
print("[gate] node --check on the three scripts; the v104.3 hunks present; the old pin layer gone")

t = SRC
# ------------------------------------------------------------------------------------------------ header and names
doc_end = t.index('"""', 3) + 3
t = '''"""Release 1.72.373 (HAD-375, design system v104.3, with Codex): one scroll on the phone and places named with the icon of
their kind. GENERATED by gen_deploy373.py from deploy372.py; do not edit by hand: change the sources and run the generator again
(every file is pinned by MD5).

Writes: assets/project-stage/world/world.js + world.css (the dock, the touch rule, the walk's own full screen, the consult pill,
the pins' icons; P9c's example hooks ride along inert: no page config names examples until 1.72.379), assets/arealife/areamap.js
(the kinds' icons, collision, names from zoom 14), assets/arealife/place-icons.js (NEW), inc/project-experience.php (one enqueue,
on the live text), nadlan-config.php (the version, on the live text). No post, no meta. Rolls back on any failed check: the files
from .bak373, the new file removed. The record deploy-result-373.json is written as soon as the files are written.

  python scripts/project-stage/deploy373.py [--dry | --rollback]
"""''' + t[doc_end:]
t = must_replace(t, 'BAK = ".bak379"', 'BAK = ".bak380"')
t = must_replace(t, "NadLan-PS379/1.0", "NadLan-PS380/1.0")
t = must_replace(t, "NS = 'nadlan-ps379-'", "NS = 'nadlan-ps380-'")
t = must_replace(t, 'f"x-tmp-ps379-ops-{int(time.time())}"', 'f"x-tmp-ps380-ops-{int(time.time())}"')
t = must_replace(t, "			$kh_write = array(); // 1.72.379 writes no post", "			$kh_write = array(); // 1.72.380 writes no post")

# ------------------------------------------------------------------------------------------------ the checks: the same pages, at the new version, plus v104.3
cs, ce = t.index("CHECKS = ["), t.index("H1_EXACTLY_ONE = [")
checks = t[cs:ce]
n_ver = checks.count("1.72.379")
checks = checks.replace("1.72.379", V)
ASSET = "/wp-content/plugins/nadlan-config/"
extra = f'''# 1.72.380 (v104.9): the fold headings count as controls for the WhatsApp bar and the accessibility corner
CHECKS += [
    ("/projects/hamedina/", ["#nlps-view-cta button,#nlps-view-cta a,#nlps summary')", "#nlps .nlw-compass button,#nlps .nlw-enter,#nlps summary'"], []),
    ("/projects/hamedina-ar/", ["#nlps-view-cta button,#nlps-view-cta a,#nlps summary')", "#nlps .nlw-compass button,#nlps .nlw-enter,#nlps summary'"], []),
    (RB, ["#nlps-view-cta button,#nlps-view-cta a,#nlps summary')"], []),
]
'''
t = t[:cs] + checks + extra + t[ce:]
t = must_replace(t, 'print("[rollback] restoring .bak379 files")', 'print("[rollback] restoring .bak380 files")')
# the rollback restores the live-text PHP too (it has a .bak373 from its put)
t = must_replace(t, '    for rel in ["nadlan-config.php"] + [r for r in FILES if r not in NEWFILES]:',
                 '    for rel in ["nadlan-config.php"] + PHP_RELS + [r for r in FILES if r not in NEWFILES]:')

# ------------------------------------------------------------------------------------------------ main
ms = t.index("# ---------------------------------------------------------------- main")
MAIN = r'''# ---------------------------------------------------------------- main (1.72.380: HAD-375, design v104.5, the rest of Codex's QA)
import signal  # noqa: E402

WANT_LIVE = "1.72.379"  # the checks name ?ver=1.72.380: this runner is for the release right after 1.72.379
PIN = __PIN__
NEWFILES = set(__NEWF__)
FILES = __FILES__
PHP_EDITS = __PHP_EDITS__
RESULT = os.path.join(QA, "deploy-result-380.json")
NEW = {}
for rel in FILES:
    NEW[rel] = open(os.path.join(PLUG, *rel.split("/")), "rb").read()
    if md5(NEW[rel]) != PIN[rel]:
        raise SystemExit(f"FATAL: {rel} changed since gen_deploy380.py pinned it ({md5(NEW[rel])[:10]} != {PIN[rel][:10]}); run the generator again")
HEAD = {rel: git_head("plugins/nadlan-config/" + rel) for rel in FILES if rel not in NEWFILES}
os.makedirs(os.path.join(QA, "live-backup"), exist_ok=True)


def _stop(signum, frame):  # a stop from outside (the shell's timeout, a console break): the finally still runs
    raise KeyboardInterrupt(f"signal {signum}")


for _sg in ("SIGTERM", "SIGBREAK"):
    if hasattr(signal, _sg):
        try:
            signal.signal(getattr(signal, _sg), _stop)
        except Exception:
            pass


def sweep(when):
    """every temporary release bridge (x-tmp-*-ops-*) still on the site is switched off and deleted (bridge_sweep.py's rule)"""
    s, lst = snip("GET", "")
    rows = [x for x in (lst if s == 200 and isinstance(lst, list) else []) if re.match(r"x-tmp-[a-z0-9]+-ops-", str(x.get("name", ""))) and x.get("active")]
    if BR is not None:
        rows = [x for x in rows if x.get("id") != BR or when == "end"]
    for x in rows:
        a = snip("PUT", f"/{x['id']}/deactivate", {})[0]
        d = snip("DELETE", f"/{x['id']}", None)[0]
        print(f"[sweep {when}] active bridge {x['id']} {x['name']}: deactivate {a}, delete {d}")
    if not rows:
        print(f"[sweep {when}] no active temporary bridge left (http {s})")


REC = {}


def record(state, **extra):
    """deploy-result-380.json, written at once and then updated: a run stopped from outside never loses what it wrote.
    A rolled-back run keeps its record with an empty "files" (the next runner's drift check then looks further back)."""
    REC.update({"released": REC.get("released"), "from": REC.get("from"), "state": state, "at": time.strftime("%Y-%m-%d %H:%M:%S")})
    REC.update(extra)
    tmp = RESULT + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(REC, fh, ensure_ascii=False, indent=2)
    os.replace(tmp, RESULT)
    print(f"[record] {os.path.basename(RESULT)}: {state}")


def served_exact(tag):
    """each written file as the site serves it to a page (?ver=1.72.380), byte for byte the pinned file"""
    ok = True
    for rel in FILES:
        path = "/wp-content/plugins/nadlan-config/" + rel + "?ver=1.72.380&nlv=" + tag
        try:
            s, b = req("GET", path, raw=True, auth=False, timeout=90)
        except Exception as e:
            s, b = str(e)[:60], b""
        good = s == 200 and md5(b) == PIN[rel]
        print(f"[served] {'OK ' if good else 'BAD'} {s} {rel}: {md5(b)[:10] if b else '-'} (want {PIN[rel][:10]})")
        ok = ok and good
    return ok


def icons_first(tag):
    """the Kikar and Rainbow pages load place-icons.js before areamap.js (the enqueue's dependency)"""
    ok = True
    for path in ("/projects/hamedina/", RB):
        s, html = page(path + "?nlv=" + tag)
        a, b = html.find("assets/arealife/place-icons.js?ver=1.72.380"), html.find("assets/arealife/areamap.js?ver=1.72.380")
        good = s == 200 and -1 < a < b
        print(f"[icons] {'OK ' if good else 'BAD'} {path}: place-icons at {a}, areamap at {b}")
        ok = ok and good
    return ok


def run_checks(tag):
    bad = verify_pages("ps380" + tag + str(int(time.time())))
    if not bad and not served_exact("ps380s" + tag + str(int(time.time()))):
        bad = ["served-files"]
    if not bad and not icons_first("ps380i" + tag + str(int(time.time()))):
        bad = ["icons-first"]
    if not bad and not verify_order("ps380o" + tag + str(int(time.time()))):
        bad = ["order"]
    if not bad and not verify_home_order("ps380h" + tag + str(int(time.time()))):
        bad = ["home-order"]
    if not bad and not verify_kh("ps380k" + tag + str(int(time.time()))):
        bad = ["kikar-hamedina"]
    return bad


created = False
try:
    sweep("start")
    bridge_up()
    before = {}
    if "--rollback" in ARGS:
        rollback(True)
        wait_version(LIVE_VER)
        if os.path.exists(RESULT):
            REC.update(json.load(open(RESULT, encoding="utf-8")))
            REC["rolled_back_files"] = REC.get("files") or REC.get("rolled_back_files") or {}
            record("rolled back (--rollback)", files={})
        raise SystemExit(0)
    if LIVE_VER != WANT_LIVE:
        raise SystemExit(f"FATAL: live is {LIVE_VER}, this runner is for {WANT_LIVE} -> 1.72.380 (its checks name the version); regenerate it")

    LIVE = {}
    for rel in FILES:
        cur = live_get(rel)
        if rel in NEWFILES:
            if not cur.get("missing"):
                raise SystemExit(f"FATAL: {rel} already exists on the site; this release makes it new")
            print(f"[drift] {rel}: not on the site yet (new)")
            continue
        if cur.get("missing"):
            raise SystemExit("FATAL live file missing: " + rel)
        LIVE[rel] = base64.b64decode(cur["b64"])
        print(f"[drift] live {rel} {md5(LIVE[rel])[:10]} vs 65af09be {md5(HEAD[rel])[:10] if HEAD[rel] else '-'}")
        prev = None
        for n in range(379, 329, -1):  # the last release that wrote the file (a rolled-back record has no "files"); else 65af09be
            p = os.path.join(QA, f"deploy-result-{n}.json")
            if os.path.exists(p):
                prev = (json.load(open(p, encoding="utf-8")).get("files") or {}).get(rel)
                if prev:
                    print(f"        last written by 1.72.{n}: {prev[:10]}")
                    break
        if prev:
            if md5(LIVE[rel]) != prev:
                raise SystemExit(f"FATAL: live {rel} is not what the last release wrote; diff it before replacing it")
        elif HEAD[rel] is None or LIVE[rel].replace(CRLF, LF) != HEAD[rel].replace(CRLF, LF):
            raise SystemExit(f"FATAL: live {rel} differs from 65af09be; diff it before replacing it")
    # the PHP: each edit on its file's LIVE text, anchored exactly once, never twice (whatever else is live there stays byte for byte)
    LIVEP, NEWP = {}, {}
    for prel, pold, pnew in PHP_EDITS:
        cur_php = live_get(prel)
        live_php = base64.b64decode(cur_php["b64"])
        ptext = live_php.decode("utf-8")
        if ptext.count(pold) != 1 or pnew in ptext:
            raise SystemExit(f"FATAL: the live {prel} does not have the one list this release edits (x{ptext.count(pold)})")
        LIVEP[prel] = live_php
        NEWP[prel] = ptext.replace(pold, pnew).encode("utf-8")
        php_lint(NEWP[prel], prel + " (live text + #nlps summary)")
    cur_main = live_get("nadlan-config.php")
    live_main = base64.b64decode(cur_main["b64"])
    stamp = time.strftime("%Y%m%dT%H%M%S")
    if not DRY:
        for rel in LIVE:
            open(os.path.join(QA, "live-backup", rel.replace("assets/", "").replace("/", "-") + f".{stamp}.live"), "wb").write(LIVE[rel])
        for prel in LIVEP:
            open(os.path.join(QA, "live-backup", prel.replace("inc/", "") + f".{stamp}.live"), "wb").write(LIVEP[prel])
        open(os.path.join(QA, "live-backup", f"nadlan-config.php.{stamp}.live"), "wb").write(live_main)

    # the version bump, on the live text
    text = live_main.decode("utf-8")
    m = re.search(r"\* Version: (\d+)\.(\d+)\.(\d+)", text)
    old = ".".join(m.groups())
    new = f"{m.group(1)}.{m.group(2)}.{int(m.group(3)) + 1}"
    if new != "1.72.380":
        raise SystemExit(f"FATAL: the bump would be {old} -> {new}, not 1.72.380")
    for a, b2 in ((f" * Version: {old}", f" * Version: {new}"), (f"define( 'NADLAN_CONFIG_VERSION', '{old}' )", f"define( 'NADLAN_CONFIG_VERSION', '{new}' )")):
        n = text.count(a)
        if n != 1:
            raise SystemExit(f"FATAL anchor x{n} in nadlan-config.php: {a}")
        text = text.replace(a, b2)
    if text.count("'project-stage', 'together'") != 1 or text.count("'home-v3', 'pro-card', 'cta-sheet' ) as $nadlan_mod") != 1:
        raise SystemExit("FATAL: the live module list is not the one 1.72.372-379 carry")
    new_main = text.encode("utf-8")
    php_lint(new_main, "nadlan-config.php (live text, bumped)")
    print(f"[plan] {old} -> {new}; writing {len(FILES)} files ({len(NEWFILES)} new): {', '.join(FILES)}; PHP on the live text: {', '.join(LIVEP)} (#nlps summary)")
    print("[plan] no post, no meta")
    if DRY:
        print("[dry] no writes")
        raise SystemExit(0)

    REC.update({"released": new, "from": old, "live_before": dict({rel: md5(LIVE[rel]) for rel in LIVE}, **{"nadlan-config.php": md5(live_main)}, **{p: md5(b) for p, b in LIVEP.items()})})
    FILES_MD5 = dict({rel: md5(NEW[rel]) for rel in FILES}, **{"nadlan-config.php": md5(new_main)}, **{p: md5(b) for p, b in NEWP.items()})
    try:
        created = True
        for rel in FILES:
            put(rel, NEW[rel], expect=("missing" if rel in NEWFILES else md5(LIVE[rel])))
        for prel in NEWP:
            put(prel, NEWP[prel], expect=md5(LIVEP[prel]))
        put("nadlan-config.php", new_main, expect=md5(live_main))
        record("written, checks pending", files=FILES_MD5)
    except BaseException as e:  # a write refused half way (drift, md5, a stop from outside): put everything back
        print("[FAIL] during writes:", e)
        rollback(created)
        if REC.get("released"):
            record("rolled back during the writes: " + str(e)[:200], files={}, rolled_back_files=FILES_MD5)
        raise
    print("[purge]", ops({"purge": 1}, "purge"))

    healthy = wait_version(new)
    bad = run_checks("a") if healthy else ["health"]
    after = speed("after") if healthy else {}
    if bad:
        print("[checks] first round:", bad, "- purge and look again")
        ops({"purge": 1}, "purge again")
        time.sleep(12)
        healthy = wait_version(new, 45)
        bad = run_checks("b") if healthy else ["health"]
    if bad:
        print("[FAIL] pages:", bad)
        rollback(created)
        wait_version(old, 60)
        record("rolled back after the checks: " + ", ".join(bad), files={}, rolled_back_files=FILES_MD5)
        raise SystemExit("ROLLED BACK")
    record("released and verified", files=FILES_MD5,
           checks="verify_pages (+ the v104.3 lines) + served_exact (the three files at ?ver=1.72.380, byte for byte) + icons_first + verify_order + verify_home_order + verify_kh: OK")
    json.dump({"before": before, "after": after}, open(os.path.join(QA, "speed-380.json"), "w", encoding="utf-8"), indent=2)
    print("RELEASE 1.72.380 LIVE: v104.9: the fold headings count as controls for the WhatsApp bar and the accessibility corner (WCAG 2.4.11)")


finally:
    try:
        bridge_down()
    except BaseException as e:
        print("[bridge] down failed:", e)
    try:
        sweep("end")
    except BaseException as e:
        print("[sweep end] failed:", e)
'''
MAIN = (MAIN.replace("__PIN__", json.dumps(PIN, indent=4)).replace("__FILES__", json.dumps(FILES)).replace("__NEWF__", json.dumps(NEWF))
        .replace("__PHP_EDITS__", json.dumps(PHP_EDITS, ensure_ascii=False)))
t = t[:ms] + MAIN
# PHP_REL is used by rollback() (defined above main): give it a module-level name early
t = must_replace(t, 'BAK = ".bak380"', 'BAK = ".bak380"\nPHP_RELS = ["inc/conversion-cta.php", "inc/project-stage.php"]  # 1.72.380: edited on the live text, restored from .bak380 on rollback')
io.open(OUT, "w", encoding="utf-8", newline="\n").write(t)
r = subprocess.run([sys.executable, "-m", "py_compile", OUT], capture_output=True, text=True)
if r.returncode:
    raise SystemExit("FATAL: deploy380.py does not compile: " + r.stderr)
bs = t.index("BRIDGE = r'''") + len("BRIDGE = r'''")
bridge_php = "<?php\n" + t[bs:t.index("'''", bs)].replace("__TOKEN__", "x" * 48).replace("__BAK__", ".bak380").replace("__NS__", "nadlan-ps380-xxxxxxxx")
tmp = os.path.join(os.environ.get("TEMP", "."), "bridge380-lint.php")
open(tmp, "w", encoding="utf-8").write(bridge_php)
r = subprocess.run(["php", "-l", tmp], capture_output=True, text=True)
os.unlink(tmp)
if r.returncode:
    raise SystemExit("FATAL: the bridge PHP does not lint: " + r.stdout + r.stderr)
left = [m.start() for m in re.finditer(r"1\.72\.375", t)]
print("wrote", OUT, "|", len(t), "chars | pinned", len(PIN), "files | bridge lint ok | py_compile ok | CHECKS moved to", V, f"({n_ver} names)",
      "| '1.72.379' named", len(left), "times (WANT_LIVE, history)")
for k, v in PIN.items():
    print(f"   {v}  {k}")
