# -*- coding: utf-8 -*-
"""1.10.2026 owner order: no source names on the visible Kikar page, every fact kept.
Edits docs/research/2026-09-30-kikar-hamedina/post-{he,en,fr,ru,ar}.html in place (anchored replacements, each asserted).
The lead, nlws-prices and nlws-sale are not touched."""
import io, os, re, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
RES = r"C:\Users\777\nad-lan\nad-lan-co-il\docs\research\2026-09-30-kikar-hamedina"
NB, NN = "\u00a0", "\u202f"


def fr(s):  # French typography in the file: NBSP before : ; ?
    return s.replace(" :", NB + ":").replace(" ;", NB + ";").replace(" ?", NB + "?")


R = {}
R["he"] = [
    ("<h2>מגדלי כיכר המדינה: כל העובדות, לפי המקורות</h2>", "<h2>מגדלי כיכר המדינה: כל העובדות</h2>"),
    ("<p>כל שורה כאן מבוססת על מקור שפורסם, והמקור רשום מתחת לנתון. כשמקורות מוסרים נתון שונה, מופיעות שתי הגרסאות.</p>",
     "<p>הנתונים המרכזיים על הפרויקט, כפי שפורסמו. כשפורסמו נתונים שונים, מופיעות שתי הגרסאות.</p>"),
    ("<small>ויקיפדיה; אשטרום. במאגר המבנים של העירייה שלושת המגדלים רשומים ב-40 קומות, בגובה 160, 158.2 ו-160 מ׳, וברישום אתר הבנייה מופיעה בקשה ל-2 קומות נוספות במגדל B</small>",
     ". פורסמו גם נתונים אחרים: שלושת המגדלים בני 40 קומות, בגובה 160, 158.2 ו-160 מ׳. במגדל B הוגשה בקשה ל-2 קומות נוספות."),
    ("<small>אשטרום. לפי מאקו (24.9.2026) וגלובס (14.12.2022): 1,626 מקומות, 906 לדיירים ו-720 ציבוריים</small>",
     ". פורסם גם נתון אחר: 1,626 מקומות, 906 לדיירים ו-720 ציבוריים."),
    ("<small>גלובס, 25.9.2025; מאקו, 24.9.2026. בפרסומים מ-2021 ו-2022 נכתב כ-50 דונם</small>", ". בפרסומים מ-2021 ו-2022 נכתב כ-50 דונם."),
    # nlws-when
    ("כל אחד עם המקור והתאריך שלו:", "כל אחד עם התאריך שלו:"),
    ("<tr><td>עיריית תל אביב-יפו, רישום אתר הבנייה</td>", "<tr><td>עיריית תל אביב-יפו</td>"),
    ("מנכ״ל ברקת קפיטל (גלובס)</td>", "מנכ״ל ברקת קפיטל</td>"),
    ("<tr><td>גלובס</td>", "<tr><td>דיווח בתקשורת</td>", 2),
    ("<tr><td>ביזפורטל</td>", "<tr><td>דיווח בתקשורת</td>"),
    ("<tr><td>אלקטרה, עמוד הפרויקט</td>", "<tr><td>אלקטרה</td>"),
    ("<tr><td>ויקיפדיה</td>", "<tr><td>פרסום נוסף</td>"),
    ("<tr><td>אשטרום, עמוד הפרויקט</td>", "<tr><td>אשטרום</td>"),
    ("<td>נקרא ב-30.9.2026</td>", "<td>נכון ל-30.9.2026</td>", 3),
    (", לפי מנהל הפרויקט בעיריית תל אביב-יפו (מאקו, 24.9.2026).", "."),
    # nlws-timeline
    (" (גלובס)</li>", "</li>", 5),
    (" (ילקוט הפרסומים 6614)</li>", "</li>"),
    (" (מאגרי התכניות; Project TLV)</li>", "</li>"),
    (" (עיריית תל אביב-יפו)</li>", "</li>"),
    (" (כלכליסט)</li>", "</li>"),
    (" (רישום אתר הבנייה בעירייה)</li>", "</li>"),
    (" (מאקו, 24.9.2026)</li>", "</li>"),
    # nlws-park
    (" (מאקו, 11.11.2025 ו-24.9.2026).", "."),
    (" (עיריית תל אביב-יפו, 4.8.2021; מאקו, 11.11.2025).", "."),
    # nlws-square
    (" (ויקיפדיה). בחנויות", ". בחנויות"),
    (" (ynet, 17.2.2023; TheMarker, 3.1.2025)", ""),
    (" (Jerusalem Post, 27.12.2025).", "."),
    (", לפי מרשם המקומות שבמפת הסביבה (נתוני העירייה, findplace ו-OpenStreetMap; זמני הליכה לפי Mapbox).", ", וכולם מופיעים במפת הסביבה שבעמוד."),
    # nlws-transport
    (" (משרד התחבורה, 8.9.2026)", ""),
    ('<p class="nlws-note">המרחקים בקו אווירי ממרכז המתחם וזמני ההליכה מטבעת הכיכר, לפי המידע הגאוגרפי של עיריית תל אביב-יפו, OpenStreetMap ו-Mapbox (9.2026).</p>',
     '<p class="nlws-note">המרחקים הם בקו אווירי ממרכז המתחם, וזמני ההליכה הם מטבעת הכיכר.</p>'),
    # nlws-faq
    (", לפי ויקיפדיה ואשטרום. במאגר המבנים של עיריית תל אביב-יפו שלושת המגדלים רשומים ב-40 קומות ובגובה של 158 עד 160 מטר.",
     ". פורסמו גם נתונים אחרים: שלושת המגדלים בני 40 קומות ובגובה של 158 עד 160 מטר."),
    (", לפי גלובס (2.5.2025).", "."),
    (" (כלכליסט, 28.11.2021).", "."),
    ("עם כלל ומגדל, לפי גלובס.</p>", "עם כלל ומגדל.</p>"),
    (", לפי ויקיפדיה.</p>", ".</p>"),
    (", לפי נתוני העירייה ו-OpenStreetMap.", "."),
    (", לפי תכנית העיצוב של העירייה (4.8.2021).", "."),
    ("אלקטרה וויקיפדיה מציינות אפריל 2027", "אלקטרה מציינת אפריל 2027"),
    ("אשטרום מציינת 2026 וביזפורטל כתב על סוף 2028. כל המועדים, עם המקור והתאריך, בטבלה שלמעלה.",
     "אשטרום מציינת 2026, ופורסם גם מועד של סוף 2028. כל המועדים, עם התאריכים, בטבלה שלמעלה."),
    (", לפי אשטרום, ויקיפדיה וגלובס,", ","),
    ("לפי ביזפורטל, לכל היותר", "לכל היותר"),
    ("<p>לפי אשטרום, באחת", "<p>באחת"),
    (", לפי אלקטרה,", ","),
]
R["en"] = [
    ("<h2>Kikar Hamedina Towers: the facts, with their sources</h2>", "<h2>Kikar Hamedina Towers: the facts</h2>"),
    ("<p>Every row rests on a published source, named under the value. Where sources give different figures, both versions are shown.</p>",
     "<p>The key figures on the project, as published. Where different figures were published, both versions are shown.</p>"),
    ("<small>Hebrew Wikipedia; Ashtrom. The municipal buildings register lists all three at 40 floors and 160, 158.2 and 160 m, and the building-site record notes a request for 2 more floors in tower B</small>",
     ". Another published figure lists all three at 40 floors and 160, 158.2 and 160 m. A request for 2 more floors in tower B was filed."),
    ("<small>Ashtrom. Per Mako (24.9.2026) and Globes (14.12.2022): 1,626 spaces, 906 for residents and 720 public</small>",
     ". Another published figure: 1,626 spaces, 906 for residents and 720 public."),
    ("<small>Globes, 25.9.2025; Mako, 24.9.2026. Publications from 2021 and 2022 gave about 50 dunams</small>", ". Publications from 2021 and 2022 gave about 50 dunams."),
    ("each with its source and date:", "each with its date:"),
    ("<tr><td>Tel Aviv-Yafo municipality, building-site record</td>", "<tr><td>Tel Aviv-Yafo municipality</td>"),
    ("CEO of Bareket Capital (Globes)</td>", "CEO of Bareket Capital</td>"),
    ("<tr><td>Globes</td>", "<tr><td>Press report</td>", 2),
    ("<tr><td>Bizportal</td>", "<tr><td>Press report</td>"),
    ("<tr><td>Electra, the project page</td>", "<tr><td>Electra</td>"),
    ("<tr><td>Hebrew Wikipedia</td>", "<tr><td>Another publication</td>"),
    ("<tr><td>Ashtrom, the project page</td>", "<tr><td>Ashtrom</td>"),
    ("<td>read 30.9.2026</td>", "<td>as of 30.9.2026</td>", 3),
    (", per the municipality&#8217;s project director (Mako, 24.9.2026).", "."),
    (" (Globes)</li>", "</li>", 5),
    (" (Official Gazette 6614)</li>", "</li>"),
    (" (plans databases; Project TLV)</li>", "</li>"),
    (" (Tel Aviv-Yafo municipality)</li>", "</li>"),
    (" (Calcalist)</li>", "</li>"),
    (" (the municipal building-site record)</li>", "</li>"),
    (" (Mako, 24.9.2026)</li>", "</li>"),
    (" (Mako, 11.11.2025 and 24.9.2026).", "."),
    (" (Tel Aviv-Yafo municipality, 4.8.2021; Mako, 11.11.2025).", "."),
    (" (Wikipedia). The ring", ". The ring"),
    (" (ynet, 17.2.2023; TheMarker, 3.1.2025)", ""),
    (" (Jerusalem Post, 27.12.2025).", "."),
    (", per the place registry in the area map (municipal data, findplace and OpenStreetMap; walking times by Mapbox).", ", all shown on this page&#8217;s area map."),
    (" (Ministry of Transport, 8.9.2026)", ""),
    ('<p class="nlws-note">Straight-line distances from the centre of the complex and walking times from the square&#8217;s ring, per the Tel Aviv-Yafo municipality&#8217;s open GIS data, OpenStreetMap and Mapbox (9.2026).</p>',
     '<p class="nlws-note">Distances are in a straight line from the centre of the complex, and walking times are from the square&#8217;s ring.</p>'),
    (", per Wikipedia and Ashtrom. The Tel Aviv-Yafo municipality&#8217;s buildings register lists all three at 40 floors and 158 to 160 metres.",
     ". Another published figure lists all three at 40 floors and 158 to 160 metres."),
    (", per Globes (2.5.2025).", "."),
    (" (Calcalist, 28.11.2021).", "."),
    ("with Clal and Migdal, per Globes.</p>", "with Clal and Migdal.</p>"),
    (", per Wikipedia.</p>", ".</p>"),
    (", per municipal data and OpenStreetMap. Kiosks will operate in the new park, and the municipality&#8217;s design plan (4.8.2021) includes a café of about 60 m² in the community centre.",
     ". Kiosks will operate in the new park, and a café of about 60 m² is planned in the community centre."),
    ("Electra and Wikipedia give April 2027", "Electra gives April 2027"),
    ("Ashtrom gives 2026 and Bizportal wrote of the end of 2028. Every date, with its source, is in the table above.",
     "Ashtrom gives 2026, and the end of 2028 has also been published. Every date is in the table above."),
    (", per Ashtrom, Wikipedia and Globes,", ","),
    ("Per Bizportal, at most 200 to 250", "At most 200 to 250"),
    ("<p>Per Ashtrom, one of the basement levels", "<p>One of the basement levels"),
    (", per Electra,", ","),
]
R["fr"] = [(fr(a), fr(b)) + tuple(t) for a, b, *t in [
    ("<h2>Tours Kikar Hamedina : toutes les données, avec leurs sources</h2>", "<h2>Tours Kikar Hamedina : toutes les données</h2>"),
    ("<p>Chaque ligne s’appuie sur une source publiée, citée sous la donnée. Lorsque deux sources donnent des chiffres différents, les deux versions figurent ici.</p>",
     "<p>Les principales données du projet, telles qu’elles ont été publiées. Lorsque des chiffres différents ont été publiés, les deux versions figurent ici.</p>"),
    ("<small>Wikipédia en hébreu ; Ashtrom. Le registre des bâtiments de la municipalité indique 40 étages pour les trois, avec 160, 158,2 et 160 m, et le registre des chantiers mentionne une demande de 2 étages supplémentaires pour la tour B</small>",
     ". D’autres données publiées indiquent 40 étages pour les trois, avec 160, 158,2 et 160 m. Une demande de 2 étages supplémentaires a été déposée pour la tour B."),
    ("<small>Ashtrom. Selon Mako (24/09/2026) et Globes (14/12/2022) : 1" + NN + "626 places, 906 pour les résidents et 720 publiques</small>",
     ". D’autres données publiées : 1" + NN + "626 places, 906 pour les résidents et 720 publiques."),
    ("<small>Globes, 25/09/2025 ; Mako, 24/09/2026. Des publications de 2021 et 2022 parlaient d’environ 50 dounams</small>", ". Des publications de 2021 et 2022 parlaient d’environ 50 dounams."),
    ("chacune avec sa source et sa date :", "chacune avec sa date :"),
    ("<tr><td>Municipalité de Tel Aviv-Jaffa, registre des chantiers</td>", "<tr><td>Municipalité de Tel Aviv-Jaffa</td>"),
    ("de Bareket Capital (Globes)</td>", "de Bareket Capital</td>"),
    ("<tr><td>Globes</td>", "<tr><td>Article de presse</td>", 2),
    ("<tr><td>Bizportal</td>", "<tr><td>Article de presse</td>"),
    ("<tr><td>Electra, page du projet</td>", "<tr><td>Electra</td>"),
    ("<tr><td>Wikipédia en hébreu</td>", "<tr><td>Autre publication</td>"),
    ("<tr><td>Ashtrom, page du projet</td>", "<tr><td>Ashtrom</td>"),
    ("<td>consulté le 30/09/2026</td>", "<td>au 30/09/2026</td>", 3),
    (", selon le directeur du projet à la municipalité de Tel Aviv-Jaffa (Mako, 24/09/2026).", "."),
    (" (Globes)</li>", "</li>", 5),
    (" (Journal officiel 6614)</li>", "</li>"),
    (" (bases de données des plans ; Project TLV)</li>", "</li>"),
    (" (municipalité de Tel Aviv-Jaffa)</li>", "</li>"),
    (" (Calcalist)</li>", "</li>"),
    (" (registre municipal des chantiers)</li>", "</li>"),
    (" (Mako, 24/09/2026)</li>", "</li>"),
    (" (Mako, 11/11/2025 et 24/09/2026).", "."),
    (" (municipalité de Tel Aviv-Jaffa, 04/08/2021 ; Mako, 11/11/2025).", "."),
    (" à Tel Aviv (Wikipédia). Les boutiques", " à Tel Aviv. Les boutiques"),
    (" et Dior (ynet, 17/02/2023 ; TheMarker, 03/01/2025), et Wikipédia en anglais cite aussi Saint Laurent, Givenchy et Chloé.",
     " et Dior, et l’on cite aussi Saint Laurent, Givenchy et Chloé."),
    (" (Jerusalem Post, 27/12/2025).", "."),
    (", selon le registre des lieux de la carte du quartier (données de la municipalité, findplace et OpenStreetMap ; temps de marche Mapbox).",
     ", tous présents sur la carte du quartier de cette page."),
    (" (ministère des Transports, 08/09/2026)", ""),
    ('<p class="nlws-note">Distances à vol d’oiseau depuis le centre de l’ensemble et temps de marche depuis la rue circulaire de la place, d’après les données géographiques ouvertes de la municipalité de Tel Aviv-Jaffa, OpenStreetMap et Mapbox (09/2026).</p>',
     '<p class="nlws-note">Les distances sont mesurées à vol d’oiseau depuis le centre de l’ensemble, et les temps de marche depuis la rue circulaire de la place.</p>'),
    (", selon Wikipédia et Ashtrom. Le registre des bâtiments de la municipalité de Tel Aviv-Jaffa indique 40 étages pour les trois tours, entre 158 et 160 mètres.",
     ". D’autres données publiées indiquent 40 étages pour les trois tours, entre 158 et 160 mètres."),
    (", selon Globes (2 mai 2025).", "."),
    (" (Calcalist, 28/11/2021).", "."),
    ("avec Clal et Migdal, selon Globes.</p>", "avec Clal et Migdal.</p>"),
    (", selon Wikipédia.</p>", ".</p>"),
    (", selon les données de la municipalité et OpenStreetMap.", "."),
    ("et le projet de la municipalité (04/08/2021) prévoit", "et le projet prévoit"),
    ("Electra et Wikipédia indiquent avril 2027", "Electra indique avril 2027"),
    ("Ashtrom indique 2026 et Bizportal a évoqué fin 2028. Chaque date, avec sa source, figure dans le tableau ci-dessus.",
     "Ashtrom indique 2026, et une échéance fin 2028 a également été publiée. Chaque date figure dans le tableau ci-dessus."),
    (", selon Ashtrom, Wikipédia et Globes,", ","),
    ("Selon Bizportal, 200 à 250 appartements au plus devraient", "Au plus 200 à 250 appartements devraient"),
    ("<p>Selon Ashtrom, l’un des niveaux", "<p>L’un des niveaux"),
    (", selon Electra,", ","),
    (" de la ville (Wikipédia), avec des maisons", " de la ville, avec des maisons"),
    (" le m² (Mako, 24/09/2026), quand", " le m², quand"),
    (" le m² (administration fiscale, ice, 28/04/2026).", " le m²."),
    (" (Israel Property Hub, 29/01/2026).", "."),
]]
R["ru"] = [
    ("<h2>Башни Кикар ха-Медина: все данные с источниками</h2>", "<h2>Башни Кикар ха-Медина: все данные</h2>"),
    ("<p>Каждая строка основана на опубликованном источнике, он указан под значением. Если источники расходятся, приведены обе версии.</p>",
     "<p>Основные данные о проекте в том виде, в каком они были опубликованы. Если публиковались разные цифры, приведены обе версии.</p>"),
    ("<small>Википедия на иврите; Ashtrom. В реестре зданий муниципалитета у всех трёх башен указано 40 этажей и высота 160, 158,2 и 160 м, а в реестре стройплощадок есть запрос на 2 дополнительных этажа в башне B</small>",
     ". Публиковались и другие данные: у всех трёх башен 40 этажей и высота 160, 158,2 и 160 м. На башню B подан запрос на 2 дополнительных этажа."),
    ("<small>Ashtrom. По данным Mako (24.09.2026) и Globes (14.12.2022): 1" + NB + "626 мест, 906 для жильцов и 720 общественных</small>",
     ". Публиковалась и другая цифра: 1" + NB + "626 мест, 906 для жильцов и 720 общественных."),
    ("<small>Globes, 25.09.2025; Mako, 24.09.2026. В публикациях 2021 и 2022 годов говорилось примерно о 50 дунамах</small>",
     ". В публикациях 2021 и 2022 годов говорилось примерно о 50 дунамах."),
    ("каждая с источником и датой:", "каждая со своей датой:"),
    ("<tr><td>Муниципалитет Тель-Авива-Яффо, реестр стройплощадок</td>", "<tr><td>Муниципалитет Тель-Авива-Яффо</td>"),
    ("директор Bareket Capital (Globes)</td>", "директор Bareket Capital</td>"),
    ("<tr><td>Globes</td>", "<tr><td>Публикация в прессе</td>", 2),
    ("<tr><td>Bizportal</td>", "<tr><td>Публикация в прессе</td>"),
    ("<tr><td>Electra, страница проекта</td>", "<tr><td>Electra</td>"),
    ("<tr><td>Википедия на иврите</td>", "<tr><td>Другая публикация</td>"),
    ("<tr><td>Ashtrom, страница проекта</td>", "<tr><td>Ashtrom</td>"),
    ("<td>просмотрено 30.09.2026</td>", "<td>по состоянию на 30.09.2026</td>", 3),
    (", по словам директора проекта в муниципалитете Тель-Авива-Яффо (Mako, 24.09.2026).", "."),
    (" (Globes)</li>", "</li>", 5),
    (" (Официальный вестник 6614)</li>", "</li>"),
    (" (базы данных планов; Project TLV)</li>", "</li>"),
    (" (муниципалитет Тель-Авива-Яффо)</li>", "</li>"),
    (" (Calcalist)</li>", "</li>"),
    (" (реестр стройплощадок муниципалитета)</li>", "</li>"),
    (" (Mako, 24.09.2026)</li>", "</li>"),
    (" (Mako, 11.11.2025 и 24.09.2026).", "."),
    (" (муниципалитет Тель-Авива-Яффо, 04.08.2021; Mako, 11.11.2025).", "."),
    (" Тель-Авива (Википедия). В бутиках", " Тель-Авива. В бутиках"),
    (" (ynet, 17.02.2023; TheMarker, 03.01.2025)", ""),
    (" (Jerusalem Post, 27.12.2025).", "."),
    (", по реестру мест на карте района (данные муниципалитета, findplace и OpenStreetMap; время пешком по Mapbox).", ", все они есть на карте района на этой странице."),
    (" (Министерство транспорта, 08.09.2026)", ""),
    ('<p class="nlws-note">Расстояния по прямой от центра комплекса и время пешком от кольцевой улицы площади, по открытым геоданным муниципалитета Тель-Авива-Яффо, OpenStreetMap и Mapbox (09.2026).</p>',
     '<p class="nlws-note">Расстояния указаны по прямой от центра комплекса, время пешком от кольцевой улицы площади.</p>'),
    (", по данным Википедии и Ashtrom. В реестре зданий муниципалитета Тель-Авива-Яффо у всех трёх башен указано 40 этажей и высота от 158 до 160 метров.",
     ". Публиковались и другие данные: у всех трёх башен 40 этажей и высота от 158 до 160 метров."),
    (", по данным Globes (02.05.2025).", "."),
    ("<p>По данным Mako (24.09.2026), сделки в башнях", "<p>Сделки в башнях"),
    (" за м² (Globes, 02.05.2025).", " за м²."),
    (" за м² (Налоговое управление, ice, 28.04.2026).", " за м²."),
    (" (Calcalist, 28.11.2021).", "."),
    ("Clal и Migdal, по данным Globes.</p>", "Clal и Migdal.</p>"),
    (", по данным Википедии.</p>", ".</p>"),
    (", по данным муниципалитета и OpenStreetMap.", "."),
    ("а по проекту муниципалитета (04.08.2021) в общинном центре предусмотрено", "а в общинном центре по проекту предусмотрено"),
    ("Electra и Википедия называют апрель 2027 года", "Electra называет апрель 2027 года"),
    ("Ashtrom указывает 2026 год, а Bizportal писал о конце 2028 года. Все даты с источниками приведены в таблице выше.",
     "Ashtrom указывает 2026 год, а также публиковался срок: конец 2028 года. Все даты приведены в таблице выше."),
    (", по данным Ashtrom, Википедии и Globes,", ","),
    ("По данным Bizportal, на рынок выйдут", "На рынок выйдут"),
    ("<p>По данным Ashtrom, на одном", "<p>На одном"),
    (", по данным Electra,", ","),
    (" (Israel Property Hub, 29.01.2026).", "."),
]
R["ar"] = [
    ("<h2>أبراج كيكار همدينا: كل المعطيات مع مصادرها</h2>", "<h2>أبراج كيكار همدينا: كل المعطيات</h2>"),
    ("<p>كل سطر هنا يستند إلى مصدر منشور مذكور تحت المعطى. وحين تختلف المصادر في رقم ما، تظهر الروايتان معاً.</p>",
     "<p>أهم المعطيات عن المشروع كما نُشرت. وحين نُشرت أرقام مختلفة، تظهر الروايتان معاً.</p>"),
    ("<small>ويكيبيديا العبرية؛ Ashtrom. في سجل المباني لدى البلدية تظهر الأبراج الثلاثة بـ40 طابقاً وبارتفاع 160 و158.2 و160 م، وفي سجل مواقع البناء طلب لإضافة طابقين إلى البرج B</small>",
     ". ونُشرت أيضاً معطيات أخرى: الأبراج الثلاثة من 40 طابقاً وبارتفاع 160 و158.2 و160 م، وقُدّم طلب لإضافة طابقين إلى البرج B."),
    ("<small>Ashtrom. ووفق Mako (24.9.2026) وGlobes (14.12.2022): 1,626 موقفاً، منها 906 للسكان و720 عامة</small>",
     ". ونُشر أيضاً رقم آخر: 1,626 موقفاً، منها 906 للسكان و720 عامة."),
    ("<small>Globes، 25.9.2025؛ Mako، 24.9.2026. في منشورات من 2021 و2022 ذُكرت مساحة نحو 50 دونماً</small>",
     ". وفي منشورات من 2021 و2022 ذُكرت مساحة نحو 50 دونماً."),
    ("كل منها مع مصدره وتاريخه:", "كل منها مع تاريخه:"),
    ("<tr><td>بلدية تل أبيب يافا، سجل مواقع البناء</td>", "<tr><td>بلدية تل أبيب يافا</td>"),
    ("لـBareket Capital (Globes)</td>", "لـBareket Capital</td>"),
    ("<tr><td>Globes</td>", "<tr><td>تقرير صحفي</td>", 2),
    ("<tr><td>Bizportal</td>", "<tr><td>تقرير صحفي</td>"),
    ("<tr><td>Electra، صفحة المشروع</td>", "<tr><td>Electra</td>"),
    ("<tr><td>ويكيبيديا العبرية</td>", "<tr><td>منشور آخر</td>"),
    ("<tr><td>Ashtrom، صفحة المشروع</td>", "<tr><td>Ashtrom</td>"),
    ("<td>اطُّلع عليها في 30.9.2026</td>", "<td>حتى تاريخ 30.9.2026</td>", 3),
    ("، وفق مدير المشروع في بلدية تل أبيب يافا (Mako، 24.9.2026).", "."),
    (" (Globes)</li>", "</li>", 5),
    (" (الجريدة الرسمية 6614)</li>", "</li>"),
    (" (قواعد بيانات المخططات؛ Project TLV)</li>", "</li>"),
    (" (بلدية تل أبيب يافا)</li>", "</li>"),
    (" (Calcalist)</li>", "</li>"),
    (" (سجل مواقع البناء في البلدية)</li>", "</li>"),
    (" (Mako، 24.9.2026)</li>", "</li>"),
    (" (Mako، 11.11.2025 و24.9.2026).", "."),
    (" (بلدية تل أبيب يافا، 4.8.2021؛ Mako، 11.11.2025).", "."),
    (" (ويكيبيديا). وفي متاجر", ". وفي متاجر"),
    (" (ynet، 17.2.2023؛ TheMarker، 3.1.2025)", ""),
    (" (Jerusalem Post، 27.12.2025).", "."),
    ("، وفق سجل الأماكن في خريطة المنطقة (بيانات البلدية وfindplace وOpenStreetMap؛ مدة المشي وفق Mapbox).", "، وكلها تظهر في خريطة المنطقة في هذه الصفحة."),
    (" (وزارة المواصلات، 8.9.2026)", ""),
    ("، وفق البيانات الجغرافية المفتوحة لبلدية تل أبيب يافا وOpenStreetMap وMapbox (9.2026).", "."),
    ("، وفق ويكيبيديا وAshtrom. وفي سجل المباني لدى بلدية تل أبيب يافا تظهر الأبراج الثلاثة بـ40 طابقاً وبارتفاع بين 158 و160 متراً.",
     ". ونُشرت أيضاً معطيات أخرى: الأبراج الثلاثة من 40 طابقاً وبارتفاع بين 158 و160 متراً."),
    ("، وفق Globes (2.5.2025).", "."),
    ("<p>وفق Mako (24.9.2026)، يبلغ متوسط", "<p>يبلغ متوسط"),
    (" للمتر المربع (Globes، 2.5.2025).", " للمتر المربع."),
    (" للمتر المربع (سلطة الضرائب، ice، 28.4.2026).", " للمتر المربع."),
    (" (Calcalist، 28.11.2021).", "."),
    ("مع Clal وMigdal، وفق Globes.</p>", "مع Clal وMigdal.</p>"),
    ("لعلامات عالمية، وفق ويكيبيديا. واسمه", "لعلامات عالمية. واسمه"),
    ("، وفق بيانات البلدية وOpenStreetMap.", "."),
    ("ويتضمن تصميم البلدية (4.8.2021) مقهى", "ويتضمن التصميم مقهى"),
    (" (Mako، 24.9.2026؛ بلدية تل أبيب يافا، 4.8.2021).", "."),
    ("تذكر Electra وويكيبيديا نيسان 2027", "تذكر Electra نيسان 2027"),
    ("وتذكر Ashtrom عام 2026، وكتب Bizportal عن نهاية 2028. كل المواعيد، مع مصادرها وتواريخها، في الجدول أعلاه.",
     "وتذكر Ashtrom عام 2026، ونُشر أيضاً موعد في نهاية 2028. كل المواعيد، مع تواريخها، في الجدول أعلاه."),
    ("، وفق Ashtrom وويكيبيديا وGlobes،", "،"),
    ("ووفق Bizportal، من المتوقع", "ومن المتوقع"),
    ("<p>وفق Ashtrom، ستُبنى", "<p>ستُبنى"),
    ("، وفق Electra،", "،"),
    (" (Israel Property Hub، 29.1.2026).", "."),
    ("، وفق Ashtrom، بينما يذكر Mako (24.9.2026) وGlobes (14.12.2022) رقم 1,626 موقفاً", "، ونُشر أيضاً رقم 1,626 موقفاً"),
    (" (Mako، 24.9.2026).</p>", ".</p>"),
]

SMALL = re.compile(r"<small>.*?</small>", re.S)
bad = 0
OUT = {}
for L in ("he", "en", "fr", "ru", "ar"):
    p = os.path.join(RES, f"post-{L}.html")
    s = io.open(p, encoding="utf-8", newline="").read()
    for item in R[L]:
        a, b = item[0], item[1]
        n = item[2] if len(item) > 2 else 1
        c = s.count(a)
        if c != n:
            print(f"{L}: anchor x{c} (want {n}): {a[:90]!r}")
            bad += 1
            continue
        s = s.replace(a, b)
    # the facts table: every remaining <small> is sources only
    i = s.index('id="nlws-facts"'); j = s.index("</section>", i)
    seg = s[i:j]
    left = SMALL.findall(seg)
    s = s[:i] + SMALL.sub("", seg) + s[j:]
    print(L, "replacements:", len(R[L]), "| source-only <small> removed:", len(left), "| <small> left anywhere:", s.count("<small>"))
    OUT[L] = (p, s)
if bad:
    raise SystemExit(f"{bad} anchors failed; nothing written")
if "--write" in sys.argv:
    for L, (p, s) in OUT.items():
        io.open(p, "w", encoding="utf-8", newline="\n").write(s)
    print("written:", ", ".join(OUT))
else:
    print("dry run OK (pass --write to write)")
