/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinalJusticeRouteImport } from './routes/final.justice'
import { Route as FinalNadlanRouteImport } from './routes/final.nadlan'
import { Route as JusticeAuthorityFirstRouteImport } from './routes/justice.authority-first'
import { Route as JusticeDualAudienceRouteImport } from './routes/justice.dual-audience'
import { Route as JusticeProductFirstRouteImport } from './routes/justice.product-first'
import { Route as NadlanAuthorityFirstRouteImport } from './routes/nadlan.authority-first'
import { Route as NadlanMapFirstRouteImport } from './routes/nadlan.map-first'
import { Route as NadlanToolsFirstRouteImport } from './routes/nadlan.tools-first'
import { Route as ProductionJusticeIndexRouteImport } from './routes/production.justice.index'
import { Route as ProductionJusticeLegalAiDeskRouteImport } from './routes/production.justice.legal-ai-desk'
import { Route as ProductionJusticeLegalSimulationRouteImport } from './routes/production.justice.legal-simulation'
import { Route as ProductionNadlanIndexRouteImport } from './routes/production.nadlan.index'
import { Route as ProductionNadlanMeetingRouteImport } from './routes/production.nadlan.meeting'
import { Route as ProductionNadlanPostListingRouteImport } from './routes/production.nadlan.post-listing'
import { Route as ProductionNadlanProjectsIndexRouteImport } from './routes/production.nadlan.projects.index'
import { Route as ProductionNadlanProjectsRainbowTelAvivRouteImport } from './routes/production.nadlan.projects.rainbow-tel-aviv'
import { Route as ProductionNadlanPropertiesIndexRouteImport } from './routes/production.nadlan.properties.index'
import { Route as ProductionNadlanPropertiesBakaDemoRouteImport } from './routes/production.nadlan.properties.baka-demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalJusticeRoute = FinalJusticeRouteImport.update({
  id: '/final/justice',
  path: '/final/justice',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalNadlanRoute = FinalNadlanRouteImport.update({
  id: '/final/nadlan',
  path: '/final/nadlan',
  getParentRoute: () => rootRouteImport,
} as any)
const JusticeAuthorityFirstRoute = JusticeAuthorityFirstRouteImport.update({
  id: '/justice/authority-first',
  path: '/justice/authority-first',
  getParentRoute: () => rootRouteImport,
} as any)
const JusticeDualAudienceRoute = JusticeDualAudienceRouteImport.update({
  id: '/justice/dual-audience',
  path: '/justice/dual-audience',
  getParentRoute: () => rootRouteImport,
} as any)
const JusticeProductFirstRoute = JusticeProductFirstRouteImport.update({
  id: '/justice/product-first',
  path: '/justice/product-first',
  getParentRoute: () => rootRouteImport,
} as any)
const NadlanAuthorityFirstRoute = NadlanAuthorityFirstRouteImport.update({
  id: '/nadlan/authority-first',
  path: '/nadlan/authority-first',
  getParentRoute: () => rootRouteImport,
} as any)
const NadlanMapFirstRoute = NadlanMapFirstRouteImport.update({
  id: '/nadlan/map-first',
  path: '/nadlan/map-first',
  getParentRoute: () => rootRouteImport,
} as any)
const NadlanToolsFirstRoute = NadlanToolsFirstRouteImport.update({
  id: '/nadlan/tools-first',
  path: '/nadlan/tools-first',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionJusticeIndexRoute = ProductionJusticeIndexRouteImport.update({
  id: '/production/justice/',
  path: '/production/justice/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionJusticeLegalAiDeskRoute =
  ProductionJusticeLegalAiDeskRouteImport.update({
    id: '/production/justice/legal-ai-desk',
    path: '/production/justice/legal-ai-desk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionJusticeLegalSimulationRoute =
  ProductionJusticeLegalSimulationRouteImport.update({
    id: '/production/justice/legal-simulation',
    path: '/production/justice/legal-simulation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionNadlanIndexRoute = ProductionNadlanIndexRouteImport.update({
  id: '/production/nadlan/',
  path: '/production/nadlan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionNadlanMeetingRoute = ProductionNadlanMeetingRouteImport.update({
  id: '/production/nadlan/meeting',
  path: '/production/nadlan/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionNadlanPostListingRoute =
  ProductionNadlanPostListingRouteImport.update({
    id: '/production/nadlan/post-listing',
    path: '/production/nadlan/post-listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionNadlanProjectsIndexRoute =
  ProductionNadlanProjectsIndexRouteImport.update({
    id: '/production/nadlan/projects/',
    path: '/production/nadlan/projects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionNadlanProjectsRainbowTelAvivRoute =
  ProductionNadlanProjectsRainbowTelAvivRouteImport.update({
    id: '/production/nadlan/projects/rainbow-tel-aviv',
    path: '/production/nadlan/projects/rainbow-tel-aviv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionNadlanPropertiesIndexRoute =
  ProductionNadlanPropertiesIndexRouteImport.update({
    id: '/production/nadlan/properties/',
    path: '/production/nadlan/properties/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionNadlanPropertiesBakaDemoRoute =
  ProductionNadlanPropertiesBakaDemoRouteImport.update({
    id: '/production/nadlan/properties/baka-demo',
    path: '/production/nadlan/properties/baka-demo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final/justice': typeof FinalJusticeRoute
  '/final/nadlan': typeof FinalNadlanRoute
  '/justice/authority-first': typeof JusticeAuthorityFirstRoute
  '/justice/dual-audience': typeof JusticeDualAudienceRoute
  '/justice/product-first': typeof JusticeProductFirstRoute
  '/nadlan/authority-first': typeof NadlanAuthorityFirstRoute
  '/nadlan/map-first': typeof NadlanMapFirstRoute
  '/nadlan/tools-first': typeof NadlanToolsFirstRoute
  '/production/justice/legal-ai-desk': typeof ProductionJusticeLegalAiDeskRoute
  '/production/justice/legal-simulation': typeof ProductionJusticeLegalSimulationRoute
  '/production/nadlan/meeting': typeof ProductionNadlanMeetingRoute
  '/production/nadlan/post-listing': typeof ProductionNadlanPostListingRoute
  '/production/justice/': typeof ProductionJusticeIndexRoute
  '/production/nadlan/': typeof ProductionNadlanIndexRoute
  '/production/nadlan/projects/rainbow-tel-aviv': typeof ProductionNadlanProjectsRainbowTelAvivRoute
  '/production/nadlan/properties/baka-demo': typeof ProductionNadlanPropertiesBakaDemoRoute
  '/production/nadlan/projects/': typeof ProductionNadlanProjectsIndexRoute
  '/production/nadlan/properties/': typeof ProductionNadlanPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final/justice': typeof FinalJusticeRoute
  '/final/nadlan': typeof FinalNadlanRoute
  '/justice/authority-first': typeof JusticeAuthorityFirstRoute
  '/justice/dual-audience': typeof JusticeDualAudienceRoute
  '/justice/product-first': typeof JusticeProductFirstRoute
  '/nadlan/authority-first': typeof NadlanAuthorityFirstRoute
  '/nadlan/map-first': typeof NadlanMapFirstRoute
  '/nadlan/tools-first': typeof NadlanToolsFirstRoute
  '/production/justice/legal-ai-desk': typeof ProductionJusticeLegalAiDeskRoute
  '/production/justice/legal-simulation': typeof ProductionJusticeLegalSimulationRoute
  '/production/nadlan/meeting': typeof ProductionNadlanMeetingRoute
  '/production/nadlan/post-listing': typeof ProductionNadlanPostListingRoute
  '/production/justice': typeof ProductionJusticeIndexRoute
  '/production/nadlan': typeof ProductionNadlanIndexRoute
  '/production/nadlan/projects/rainbow-tel-aviv': typeof ProductionNadlanProjectsRainbowTelAvivRoute
  '/production/nadlan/properties/baka-demo': typeof ProductionNadlanPropertiesBakaDemoRoute
  '/production/nadlan/projects': typeof ProductionNadlanProjectsIndexRoute
  '/production/nadlan/properties': typeof ProductionNadlanPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final/justice': typeof FinalJusticeRoute
  '/final/nadlan': typeof FinalNadlanRoute
  '/justice/authority-first': typeof JusticeAuthorityFirstRoute
  '/justice/dual-audience': typeof JusticeDualAudienceRoute
  '/justice/product-first': typeof JusticeProductFirstRoute
  '/nadlan/authority-first': typeof NadlanAuthorityFirstRoute
  '/nadlan/map-first': typeof NadlanMapFirstRoute
  '/nadlan/tools-first': typeof NadlanToolsFirstRoute
  '/production/justice/legal-ai-desk': typeof ProductionJusticeLegalAiDeskRoute
  '/production/justice/legal-simulation': typeof ProductionJusticeLegalSimulationRoute
  '/production/nadlan/meeting': typeof ProductionNadlanMeetingRoute
  '/production/nadlan/post-listing': typeof ProductionNadlanPostListingRoute
  '/production/justice/': typeof ProductionJusticeIndexRoute
  '/production/nadlan/': typeof ProductionNadlanIndexRoute
  '/production/nadlan/projects/rainbow-tel-aviv': typeof ProductionNadlanProjectsRainbowTelAvivRoute
  '/production/nadlan/properties/baka-demo': typeof ProductionNadlanPropertiesBakaDemoRoute
  '/production/nadlan/projects/': typeof ProductionNadlanProjectsIndexRoute
  '/production/nadlan/properties/': typeof ProductionNadlanPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/final/justice'
    | '/final/nadlan'
    | '/justice/authority-first'
    | '/justice/dual-audience'
    | '/justice/product-first'
    | '/nadlan/authority-first'
    | '/nadlan/map-first'
    | '/nadlan/tools-first'
    | '/production/justice/legal-ai-desk'
    | '/production/justice/legal-simulation'
    | '/production/nadlan/meeting'
    | '/production/nadlan/post-listing'
    | '/production/justice/'
    | '/production/nadlan/'
    | '/production/nadlan/projects/rainbow-tel-aviv'
    | '/production/nadlan/properties/baka-demo'
    | '/production/nadlan/projects/'
    | '/production/nadlan/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/final/justice'
    | '/final/nadlan'
    | '/justice/authority-first'
    | '/justice/dual-audience'
    | '/justice/product-first'
    | '/nadlan/authority-first'
    | '/nadlan/map-first'
    | '/nadlan/tools-first'
    | '/production/justice/legal-ai-desk'
    | '/production/justice/legal-simulation'
    | '/production/nadlan/meeting'
    | '/production/nadlan/post-listing'
    | '/production/justice'
    | '/production/nadlan'
    | '/production/nadlan/projects/rainbow-tel-aviv'
    | '/production/nadlan/properties/baka-demo'
    | '/production/nadlan/projects'
    | '/production/nadlan/properties'
  id:
    | '__root__'
    | '/'
    | '/final/justice'
    | '/final/nadlan'
    | '/justice/authority-first'
    | '/justice/dual-audience'
    | '/justice/product-first'
    | '/nadlan/authority-first'
    | '/nadlan/map-first'
    | '/nadlan/tools-first'
    | '/production/justice/legal-ai-desk'
    | '/production/justice/legal-simulation'
    | '/production/nadlan/meeting'
    | '/production/nadlan/post-listing'
    | '/production/justice/'
    | '/production/nadlan/'
    | '/production/nadlan/projects/rainbow-tel-aviv'
    | '/production/nadlan/properties/baka-demo'
    | '/production/nadlan/projects/'
    | '/production/nadlan/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalJusticeRoute: typeof FinalJusticeRoute
  FinalNadlanRoute: typeof FinalNadlanRoute
  JusticeAuthorityFirstRoute: typeof JusticeAuthorityFirstRoute
  JusticeDualAudienceRoute: typeof JusticeDualAudienceRoute
  JusticeProductFirstRoute: typeof JusticeProductFirstRoute
  NadlanAuthorityFirstRoute: typeof NadlanAuthorityFirstRoute
  NadlanMapFirstRoute: typeof NadlanMapFirstRoute
  NadlanToolsFirstRoute: typeof NadlanToolsFirstRoute
  ProductionJusticeLegalAiDeskRoute: typeof ProductionJusticeLegalAiDeskRoute
  ProductionJusticeLegalSimulationRoute: typeof ProductionJusticeLegalSimulationRoute
  ProductionNadlanMeetingRoute: typeof ProductionNadlanMeetingRoute
  ProductionNadlanPostListingRoute: typeof ProductionNadlanPostListingRoute
  ProductionJusticeIndexRoute: typeof ProductionJusticeIndexRoute
  ProductionNadlanIndexRoute: typeof ProductionNadlanIndexRoute
  ProductionNadlanProjectsRainbowTelAvivRoute: typeof ProductionNadlanProjectsRainbowTelAvivRoute
  ProductionNadlanPropertiesBakaDemoRoute: typeof ProductionNadlanPropertiesBakaDemoRoute
  ProductionNadlanProjectsIndexRoute: typeof ProductionNadlanProjectsIndexRoute
  ProductionNadlanPropertiesIndexRoute: typeof ProductionNadlanPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final/justice': {
      id: '/final/justice'
      path: '/final/justice'
      fullPath: '/final/justice'
      preLoaderRoute: typeof FinalJusticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final/nadlan': {
      id: '/final/nadlan'
      path: '/final/nadlan'
      fullPath: '/final/nadlan'
      preLoaderRoute: typeof FinalNadlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justice/authority-first': {
      id: '/justice/authority-first'
      path: '/justice/authority-first'
      fullPath: '/justice/authority-first'
      preLoaderRoute: typeof JusticeAuthorityFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justice/dual-audience': {
      id: '/justice/dual-audience'
      path: '/justice/dual-audience'
      fullPath: '/justice/dual-audience'
      preLoaderRoute: typeof JusticeDualAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justice/product-first': {
      id: '/justice/product-first'
      path: '/justice/product-first'
      fullPath: '/justice/product-first'
      preLoaderRoute: typeof JusticeProductFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nadlan/authority-first': {
      id: '/nadlan/authority-first'
      path: '/nadlan/authority-first'
      fullPath: '/nadlan/authority-first'
      preLoaderRoute: typeof NadlanAuthorityFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nadlan/map-first': {
      id: '/nadlan/map-first'
      path: '/nadlan/map-first'
      fullPath: '/nadlan/map-first'
      preLoaderRoute: typeof NadlanMapFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nadlan/tools-first': {
      id: '/nadlan/tools-first'
      path: '/nadlan/tools-first'
      fullPath: '/nadlan/tools-first'
      preLoaderRoute: typeof NadlanToolsFirstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/justice/': {
      id: '/production/justice/'
      path: '/production/justice'
      fullPath: '/production/justice/'
      preLoaderRoute: typeof ProductionJusticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/justice/legal-ai-desk': {
      id: '/production/justice/legal-ai-desk'
      path: '/production/justice/legal-ai-desk'
      fullPath: '/production/justice/legal-ai-desk'
      preLoaderRoute: typeof ProductionJusticeLegalAiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/justice/legal-simulation': {
      id: '/production/justice/legal-simulation'
      path: '/production/justice/legal-simulation'
      fullPath: '/production/justice/legal-simulation'
      preLoaderRoute: typeof ProductionJusticeLegalSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/': {
      id: '/production/nadlan/'
      path: '/production/nadlan'
      fullPath: '/production/nadlan/'
      preLoaderRoute: typeof ProductionNadlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/meeting': {
      id: '/production/nadlan/meeting'
      path: '/production/nadlan/meeting'
      fullPath: '/production/nadlan/meeting'
      preLoaderRoute: typeof ProductionNadlanMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/post-listing': {
      id: '/production/nadlan/post-listing'
      path: '/production/nadlan/post-listing'
      fullPath: '/production/nadlan/post-listing'
      preLoaderRoute: typeof ProductionNadlanPostListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/projects/': {
      id: '/production/nadlan/projects/'
      path: '/production/nadlan/projects'
      fullPath: '/production/nadlan/projects/'
      preLoaderRoute: typeof ProductionNadlanProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/projects/rainbow-tel-aviv': {
      id: '/production/nadlan/projects/rainbow-tel-aviv'
      path: '/production/nadlan/projects/rainbow-tel-aviv'
      fullPath: '/production/nadlan/projects/rainbow-tel-aviv'
      preLoaderRoute: typeof ProductionNadlanProjectsRainbowTelAvivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/properties/': {
      id: '/production/nadlan/properties/'
      path: '/production/nadlan/properties'
      fullPath: '/production/nadlan/properties/'
      preLoaderRoute: typeof ProductionNadlanPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/nadlan/properties/baka-demo': {
      id: '/production/nadlan/properties/baka-demo'
      path: '/production/nadlan/properties/baka-demo'
      fullPath: '/production/nadlan/properties/baka-demo'
      preLoaderRoute: typeof ProductionNadlanPropertiesBakaDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalJusticeRoute: FinalJusticeRoute,
  FinalNadlanRoute: FinalNadlanRoute,
  JusticeAuthorityFirstRoute: JusticeAuthorityFirstRoute,
  JusticeDualAudienceRoute: JusticeDualAudienceRoute,
  JusticeProductFirstRoute: JusticeProductFirstRoute,
  NadlanAuthorityFirstRoute: NadlanAuthorityFirstRoute,
  NadlanMapFirstRoute: NadlanMapFirstRoute,
  NadlanToolsFirstRoute: NadlanToolsFirstRoute,
  ProductionJusticeLegalAiDeskRoute: ProductionJusticeLegalAiDeskRoute,
  ProductionJusticeLegalSimulationRoute: ProductionJusticeLegalSimulationRoute,
  ProductionNadlanMeetingRoute: ProductionNadlanMeetingRoute,
  ProductionNadlanPostListingRoute: ProductionNadlanPostListingRoute,
  ProductionJusticeIndexRoute: ProductionJusticeIndexRoute,
  ProductionNadlanIndexRoute: ProductionNadlanIndexRoute,
  ProductionNadlanProjectsRainbowTelAvivRoute:
    ProductionNadlanProjectsRainbowTelAvivRoute,
  ProductionNadlanPropertiesBakaDemoRoute:
    ProductionNadlanPropertiesBakaDemoRoute,
  ProductionNadlanProjectsIndexRoute: ProductionNadlanProjectsIndexRoute,
  ProductionNadlanPropertiesIndexRoute: ProductionNadlanPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

