# -*- coding: utf-8 -*-
"""Writes scripts/project-stage/had256_release.py, the HAD-256 release package module (snapshot 3 = 2ce0a741), from git.

  python scripts/had-256/make_release.py                  # snapshot 3 (2ce0a741): writes the module and proves it
  python scripts/had-256/make_release.py --snap <commit>  # the same for a later candidate (e.g. owner-wizard 2.0.1)

broker-drop.php: the 8 hunks of `git diff 6e9cf930 2ce0a741 -- plugins/nadlan-config/inc/broker-drop.php` (3 lines of
context), each as (old block, new block); every old block must be in the base text exactly once, at its turn.
owner-wizard.php: the whole file (snippet 707 is replaced whole); the module reads it from git and checks its SHA-256.
Both as Code Snippets hold them: the opening tag and the whitespace after it removed (deploydrop.py's rule), LF.
"""
import hashlib
import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
BASE = '6e9cf930'
SNAP = sys.argv[sys.argv.index('--snap') + 1] if '--snap' in sys.argv else '2ce0a741'
BD, OW = 'plugins/nadlan-config/inc/broker-drop.php', 'plugins/nadlan-config/inc/owner-wizard.php'
OUT = os.path.join(REPO, 'scripts', 'project-stage', 'had256_release.py')


def show(ref, path):
    return subprocess.run(['git', '-C', REPO, 'show', '%s:%s' % (ref, path)], capture_output=True, check=True).stdout.decode('utf-8')


def code(php):
    """the Code Snippets body: deploydrop.py's re.sub(r"^\\s*<\\?php\\s*", "", php, count=1), LF"""
    return re.sub(r"^\s*<\?php\s*", "", php.replace('\r\n', '\n'), count=1)


sha = lambda s: hashlib.sha256(s.encode('utf-8')).hexdigest()

diff = subprocess.run(['git', '-C', REPO, '-c', 'core.autocrlf=false', 'diff', '-U3', '--no-color', BASE, SNAP, '--', BD], capture_output=True, check=True).stdout.decode('utf-8')
hunks, cur = [], None
for line in diff.split('\n'):
    if line.startswith('@@'):
        cur = {'head': line, 'old': [], 'new': []}
        hunks.append(cur)
    elif cur is not None and line.startswith('\\'):
        continue
    elif cur is not None and line[:1] in (' ', '-', '+'):
        if line[:1] in (' ', '-'):
            cur['old'].append(line[1:])
        if line[:1] in (' ', '+'):
            cur['new'].append(line[1:])
if len(hunks) != 8:
    raise SystemExit('make_release: %d hunks, expected 8' % len(hunks))
pairs = [('\n'.join(h['old']) + '\n', '\n'.join(h['new']) + '\n', h['head']) for h in hunks]

base_bd, snap_bd = code(show(BASE, BD)), code(show(SNAP, BD))
t = base_bd
for i, (o, n, head) in enumerate(pairs, 1):
    if t.count(o) != 1 or base_bd.count(o) != 1:
        raise SystemExit('make_release: hunk %d old block x%d (base x%d)' % (i, t.count(o), base_bd.count(o)))
    t = t.replace(o, n)
if t != snap_bd:
    raise SystemExit('make_release: base + 8 hunks != snapshot 3')
base_ow, snap_ow = code(show(BASE, OW)), code(show(SNAP, OW))

L = []
w = L.append
w('# -*- coding: utf-8 -*-')
w('"""HAD-256 release package: the owner listing journey on x-broker-drop 1.1.4, pinned to code %s.' % SNAP)
w('GENERATED by scripts/had-256/make_release.py from git; do not edit by hand (re-run the generator).')
w('')
w('Two live Code Snippets change, nothing else (no plugin file, no page, no option):')
w('  "snippet:x-broker-drop"   the 8 HAD-256 hunks, applied to the LIVE snippet text, each anchored exactly once')
w('                            (git diff 6e9cf930 2ce0a741 -- plugins/nadlan-config/inc/broker-drop.php);')
w('  "snippet:x-owner-wizard"  snippet 707, replaced WHOLE by owner-wizard.php of %s (its live text must be the 1.0.0 base).' % SNAP)
w('Texts are Code Snippets bodies: the opening <?php tag and the whitespace after it removed (deploydrop.py\'s rule), LF.')
w('apply(rel, txt) returns the new text or raises SystemExit (drift, an anchor not found once, already applied).')
w('    python scripts/project-stage/had256_release.py     # self-check: base + package == snapshot 3 (needs git)')
w('"""')
w('import hashlib')
w('import os')
w('import re')
w('import subprocess')
w('')
w('SNAPSHOT = %r' % SNAP)
w('BASE = %r' % BASE)
w('RELS = ["snippet:x-broker-drop", "snippet:x-owner-wizard"]')
w('SNIPPET_707 = 707   # x-owner-wizard (live-read 3.10.2026: docs/qa/live-read/20261003T205055Z/snippet-707.php)')
w('# SHA-256 of the snippet bodies (UTF-8, LF)')
w('BROKER_BASE_SHA256 = %r   # x-broker-drop 1.1.3 = 6e9cf930' % sha(base_bd))
w('BROKER_NEW_SHA256 = %r    # x-broker-drop 1.1.4 at %s' % (sha(snap_bd), SNAP))
w('OWNER_BASE_SHA256 = %r    # snippet 707, x-owner-wizard 1.0.0 = 6e9cf930' % sha(base_ow))
w('OWNER_NEW_SHA256 = %r     # x-owner-wizard at %s' % (sha(snap_ow), SNAP))
w('# SHA-256 of the repo files as committed (with the opening tag, LF)')
w('FILE_SHA256 = {%r: %r, %r: %r}' % (OW, sha(show(SNAP, OW).replace('\r\n', '\n')), BD, sha(show(SNAP, BD).replace('\r\n', '\n'))))
w('')
w('_sha = lambda s: hashlib.sha256(s.encode("utf-8")).hexdigest()')
w('_HERE = os.path.dirname(os.path.abspath(__file__))')
w('_REPO = os.path.abspath(os.path.join(_HERE, "..", ".."))')
w('')
w('')
w('def _code(php):')
w('    return re.sub(r"^\\s*<\\?php\\s*", "", php.replace("\\r\\n", "\\n"), count=1)')
w('')
w('')
w('def _show(ref, path):')
w('    return subprocess.run(["git", "-C", _REPO, "show", ref + ":" + path], capture_output=True, check=True).stdout.decode("utf-8")')
w('')
w('')
w('def owner_code():')
w('    """the x-owner-wizard 2.0.0 body, read from git at the pinned commit and checked"""')
w('    c = _code(_show(SNAPSHOT, %r))' % OW)
w('    if _sha(c) != OWNER_NEW_SHA256:')
w('        raise SystemExit("had256_release: owner-wizard.php at " + SNAPSHOT + " is " + _sha(c)[:12] + ", pinned " + OWNER_NEW_SHA256[:12])')
w('    return c')
w('')
w('')
w('# the 8 hunks of x-broker-drop, in file order: (old block, new block); the old block is the anchor (exactly once)')
w('HUNKS = [')
for o, n, head in pairs:
    w('    # %s' % head)
    w('    (%r,' % o)
    w('     %r),' % n)
w(']')
w('')
w('')
w('def apply(rel, txt):')
w('    crlf = "\\r\\n" in txt')
w('    t = txt.replace("\\r\\n", "\\n")')
w('    if rel == "snippet:x-owner-wizard":')
w('        if _sha(t) == OWNER_NEW_SHA256:')
w('            raise SystemExit("had256_release: snippet 707 is already this x-owner-wizard")')
w('        if _sha(t) != OWNER_BASE_SHA256:')
w('            raise SystemExit("had256_release: snippet 707 is " + _sha(t)[:12] + ", not the 1.0.0 base " + OWNER_BASE_SHA256[:12] + " (drift: stop)")')
w('        out = owner_code()')
w('    elif rel == "snippet:x-broker-drop":')
w('        if "define( \'NL_DROP_VERSION\', \'1.1.4\' )" in t or "function nl_drop_lock_acquire(" in t:')
w('            raise SystemExit("had256_release: x-broker-drop already carries the HAD-256 hunks")')
w('        if _sha(t) != BROKER_BASE_SHA256:')
w('            print("had256_release: x-broker-drop is " + _sha(t)[:12] + ", not the 1.1.3 base " + BROKER_BASE_SHA256[:12] + "; applying by anchors")')
w('        for i, (old, new) in enumerate(HUNKS, 1):')
w('            n = t.count(old)')
w('            if n != 1:')
w('                raise SystemExit("had256_release: x-broker-drop hunk " + str(i) + " anchor is there " + str(n) + " times")')
w('            t = t.replace(old, new)')
w('        out = t')
w('    else:')
w('        raise SystemExit("had256_release: unknown rel " + rel)')
w('    return out.replace("\\n", "\\r\\n") if crlf else out')
w('')
w('')
w('if __name__ == "__main__":')
w('    b = apply("snippet:x-broker-drop", _code(_show(BASE, %r)))' % BD)
w('    assert _sha(b) == BROKER_NEW_SHA256, "x-broker-drop: base + 8 hunks != snapshot 3"')
w('    o = apply("snippet:x-owner-wizard", _code(_show(BASE, %r)))' % OW)
w('    assert _sha(o) == OWNER_NEW_SHA256')
w('    for rel, txt in (("snippet:x-broker-drop", b), ("snippet:x-owner-wizard", o)):')
w('        try:')
w('            apply(rel, txt)')
w('            raise AssertionError(rel + ": a second apply did not stop")')
w('        except SystemExit as e:')
w('            assert "already" in str(e), e')
w('    print("had256_release OK: x-broker-drop " + BROKER_BASE_SHA256[:12] + " -> " + BROKER_NEW_SHA256[:12] + " (8 hunks), snippet 707 " + OWNER_BASE_SHA256[:12] + " -> " + OWNER_NEW_SHA256[:12] + "; a second apply stops")')
io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
print('wrote', os.path.relpath(OUT, REPO), '| broker', sha(base_bd)[:12], '->', sha(snap_bd)[:12], '| owner', sha(base_ow)[:12], '->', sha(snap_ow)[:12])
