# -*- coding: utf-8 -*-
"""Writes scripts/project-stage/had256_release.py, the HAD-256 release package module (snapshot 3 = 2ce0a741), from git.

  python scripts/had-256/make_release.py                  # snapshot 3 (2ce0a741): writes the module and proves it
  python scripts/had-256/make_release.py --snap <commit>  # the same for a later candidate (e.g. owner-wizard 2.0.1)

broker-drop.php: the 8 hunks of `git diff 6e9cf930 2ce0a741 -- plugins/nadlan-config/inc/broker-drop.php` (3 lines of
context), each as (old block, new block); every old block must be in the base text exactly once, at its turn.
owner-wizard.php: the whole file (snippet 707 is replaced whole); the module reads it from git and checks its SHA-256.
Both as Code Snippets hold them: the opening tag and the whitespace after it removed (deploydrop.py's rule), LF.
"""
import hashlib
import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
BASE = '6e9cf930'
PAGES_AT = subprocess.run(['git', '-C', os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')), 'log', '-1', '--format=%h', '--', 'docs/qa/had-256/page-4958'], capture_output=True, check=True).stdout.decode().strip()
SNAP = sys.argv[sys.argv.index('--snap') + 1] if '--snap' in sys.argv else '2ce0a741'
BD, OW = 'plugins/nadlan-config/inc/broker-drop.php', 'plugins/nadlan-config/inc/owner-wizard.php'
OUT = os.path.join(REPO, 'scripts', 'project-stage', sys.argv[sys.argv.index('--out') + 1] if '--out' in sys.argv else 'had256_release.py')


def show(ref, path):
    return subprocess.run(['git', '-C', REPO, 'show', '%s:%s' % (ref, path)], capture_output=True, check=True).stdout.decode('utf-8')


def code(php):
    """the Code Snippets body: deploydrop.py's re.sub(r"^\\s*<\\?php\\s*", "", php, count=1), LF"""
    return re.sub(r"^\s*<\?php\s*", "", php.replace('\r\n', '\n'), count=1)


sha = lambda s: hashlib.sha256(s.encode('utf-8')).hexdigest()

diff = subprocess.run(['git', '-C', REPO, '-c', 'core.autocrlf=false', 'diff', '-U3', '--no-color', BASE, SNAP, '--', BD], capture_output=True, check=True).stdout.decode('utf-8')
hunks, cur = [], None
for line in diff.split('\n'):
    if line.startswith('@@'):
        cur = {'head': line, 'old': [], 'new': []}
        hunks.append(cur)
    elif cur is not None and line.startswith('\\'):
        continue
    elif cur is not None and line[:1] in (' ', '-', '+'):
        if line[:1] in (' ', '-'):
            cur['old'].append(line[1:])
        if line[:1] in (' ', '+'):
            cur['new'].append(line[1:])
if len(hunks) != 8:
    raise SystemExit('make_release: %d hunks, expected 8' % len(hunks))
pairs = [('\n'.join(h['old']) + '\n', '\n'.join(h['new']) + '\n', h['head']) for h in hunks]

base_bd, snap_bd = code(show(BASE, BD)), code(show(SNAP, BD))
t = base_bd
for i, (o, n, head) in enumerate(pairs, 1):
    if t.count(o) != 1 or base_bd.count(o) != 1:
        raise SystemExit('make_release: hunk %d old block x%d (base x%d)' % (i, t.count(o), base_bd.count(o)))
    t = t.replace(o, n)
if t != snap_bd:
    raise SystemExit('make_release: base + 8 hunks != snapshot 3')
base_ow, snap_ow = code(show(BASE, OW)), code(show(SNAP, OW))
ver = lambda c, k: re.search(r"define\( '" + k + r"', '([0-9.]+)' \)", c).group(1)
OWNER_VERSION, BROKER_VERSION = ver(snap_ow, 'NL_OWNER_VERSION'), ver(snap_bd, 'NL_DROP_VERSION')
# the owners' draft photos outside the web root, without touching wp-config.php: a guarded define at the top of the
# 707 body (read only at request time by nl_owner_private_base(); a wp-config.php define still wins)
PRELUDE = ("/* HAD-256 release: owners' draft photos are kept outside the web root, beside the WordPress folder. A define in\n"
           "   wp-config.php wins; owner-wizard reads it only while serving a request. */\n"
           "if ( ! defined( 'NL_OWNER_PRIVATE_DIR' ) ) { define( 'NL_OWNER_PRIVATE_DIR', rtrim( dirname( ABSPATH ), '/' ) . '/nl-private' ); }\n")
live_ow = PRELUDE + snap_ow
PG = os.path.join(REPO, 'docs', 'qa', 'had-256', 'page-4958')
pg = {n: io.open(os.path.join(PG, n), encoding='utf-8').read().replace('\r\n', '\n') for n in ('old.html', 'anchor.html', 'new-B-paragraph.html', 'new-A.html', 'new-B.html')}
assert pg['old.html'].count(pg['anchor.html']) == 1
assert pg['old.html'].replace(pg['anchor.html'], '') == pg['new-A.html'] and pg['old.html'].replace(pg['anchor.html'], pg['new-B-paragraph.html']) == pg['new-B.html']

L = []
w = L.append
w('# -*- coding: utf-8 -*-')
w('"""HAD-256 release package: the owner listing journey on x-broker-drop 1.1.4, pinned to code %s.' % SNAP)
w('GENERATED by scripts/had-256/make_release.py from git; do not edit by hand (re-run the generator).')
w('')
w('Two live Code Snippets change, nothing else (no plugin file, no page, no option):')
w('  "snippet:x-broker-drop"   the 8 HAD-256 hunks, applied to the LIVE snippet text, each anchored exactly once')
w('                            (git diff 6e9cf930 2ce0a741 -- plugins/nadlan-config/inc/broker-drop.php);')
w('  "snippet:x-owner-wizard"  snippet 707, replaced WHOLE by PRIVATE_PRELUDE + owner-wizard.php %s of %s (its live text must be the 1.0.0 base).' % (OWNER_VERSION, SNAP))
w('Texts are Code Snippets bodies: the opening <?php tag and the whitespace after it removed (deploydrop.py\'s rule), LF.')
w('apply(rel, txt) returns the new text or raises SystemExit (drift, an anchor not found once, already applied).')
w('    python scripts/project-stage/had256_release.py     # self-check: base + package == snapshot 3 (needs git)')
w('"""')
w('import hashlib')
w('import os')
w('import re')
w('import subprocess')
w('')
w('SNAPSHOT = %r' % SNAP)
w('SNAPSHOT_PAGES = %r   # the commit that holds docs/qa/had-256/page-4958' % PAGES_AT)
w('BASE = %r' % BASE)
w('RELS = ["snippet:x-broker-drop", "snippet:x-owner-wizard"]   # + "page:4958:A" / "page:4958:B" when main picks a copy variant')
w('SNIPPET_707 = 707   # x-owner-wizard (live-read 3.10.2026: docs/qa/live-read/20261003T205055Z/snippet-707.php)')
w('# SHA-256 of the snippet bodies (UTF-8, LF)')
w('BROKER_BASE_SHA256 = %r   # x-broker-drop 1.1.3 = 6e9cf930' % sha(base_bd))
w('BROKER_NEW_SHA256 = %r    # x-broker-drop 1.1.4 at %s' % (sha(snap_bd), SNAP))
w('OWNER_BASE_SHA256 = %r    # snippet 707, x-owner-wizard 1.0.0 = 6e9cf930' % sha(base_ow))
w('OWNER_NEW_SHA256 = %r     # x-owner-wizard at %s (the repo file without its opening tag)' % (sha(snap_ow), SNAP))
w('OWNER_LIVE_SHA256 = %r    # what snippet 707 holds after the release: PRIVATE_PRELUDE + that body' % sha(live_ow))
w('OWNER_VERSION = %r' % OWNER_VERSION)
w('BROKER_VERSION = %r' % BROKER_VERSION)
w('PRIVATE_DIR_EXPR = %r' % "rtrim( dirname( ABSPATH ), '/' ) . '/nl-private'")
w('PRIVATE_PRELUDE = %r' % PRELUDE)
w('# page 4958 (/post-listing/): the copy variants (docs/qa/had-256/page-4958). The anchor is the old paragraph block, exactly once.')
w('PAGE_ID = 4958')
w('PAGE_PATH = "post-listing"')
w('PAGE_OLD_SHA256 = %r   # the text deploydrop.py --post-listing wrote (scripts/broker-drop/pages/post-listing-he.html, LF)' % sha(pg['old.html']))
w('PAGE_ANCHOR = %r' % pg['anchor.html'])
w('PAGE_NEW = {"A": "", "B": %r}' % pg['new-B-paragraph.html'])
w('PAGE_NEW_SHA256 = {"A": %r, "B": %r}   # from the old text' % (sha(pg['new-A.html']), sha(pg['new-B.html'])))
w('# SHA-256 of the repo files as committed (with the opening tag, LF)')
w('FILE_SHA256 = {%r: %r, %r: %r}' % (OW, sha(show(SNAP, OW).replace('\r\n', '\n')), BD, sha(show(SNAP, BD).replace('\r\n', '\n'))))
w('')
w('_sha = lambda s: hashlib.sha256(s.encode("utf-8")).hexdigest()')
w('_HERE = os.path.dirname(os.path.abspath(__file__))')
w('_REPO = os.path.abspath(os.path.join(_HERE, "..", ".."))')
w('')
w('')
w('def _code(php):')
w('    return re.sub(r"^\\s*<\\?php\\s*", "", php.replace("\\r\\n", "\\n"), count=1)')
w('')
w('')
w('def _show(ref, path):')
w('    return subprocess.run(["git", "-C", _REPO, "show", ref + ":" + path], capture_output=True, check=True).stdout.decode("utf-8")')
w('')
w('')
w('def owner_code():')
w('    """the x-owner-wizard 2.0.0 body, read from git at the pinned commit and checked"""')
w('    c = _code(_show(SNAPSHOT, %r))' % OW)
w('    if _sha(c) != OWNER_NEW_SHA256:')
w('        raise SystemExit("had256_release: owner-wizard.php at " + SNAPSHOT + " is " + _sha(c)[:12] + ", pinned " + OWNER_NEW_SHA256[:12])')
w('    return c')
w('')
w('')
w('# the 8 hunks of x-broker-drop, in file order: (old block, new block); the old block is the anchor (exactly once)')
w('HUNKS = [')
for o, n, head in pairs:
    w('    # %s' % head)
    w('    (%r,' % o)
    w('     %r),' % n)
w(']')
w('')
w('')
w('def apply(rel, txt):')
w('    crlf = "\\r\\n" in txt')
w('    t = txt.replace("\\r\\n", "\\n")')
w('    if rel == "snippet:x-owner-wizard":')
w('        if _sha(t) in (OWNER_NEW_SHA256, OWNER_LIVE_SHA256):')
w('            raise SystemExit("had256_release: snippet 707 is already this x-owner-wizard")')
w('        if _sha(t) != OWNER_BASE_SHA256:')
w('            raise SystemExit("had256_release: snippet 707 is " + _sha(t)[:12] + ", not the 1.0.0 base " + OWNER_BASE_SHA256[:12] + " (drift: stop)")')
w('        out = PRIVATE_PRELUDE + owner_code()')
w('    elif rel in ("page:4958:A", "page:4958:B"):')
w('        v = rel[-1]')
w('        if (v == "B" and PAGE_NEW["B"] in t) or (v == "A" and PAGE_ANCHOR not in t and "<!-- wp:paragraph -->" not in t and "[nadlan_listing_wizard]" in t):')
w('            raise SystemExit("had256_release: page 4958 already carries copy variant " + v)')
w('        n = t.count(PAGE_ANCHOR)')
w('        if n != 1:')
w('            raise SystemExit("had256_release: page 4958 anchor (the old paragraph) is there " + str(n) + " times (drift: stop)")')
w('        out = t.replace(PAGE_ANCHOR, PAGE_NEW[v])')
w('    elif rel == "snippet:x-broker-drop":')
w('        if "define( \'NL_DROP_VERSION\', \'1.1.4\' )" in t or "function nl_drop_lock_acquire(" in t:')
w('            raise SystemExit("had256_release: x-broker-drop already carries the HAD-256 hunks")')
w('        if _sha(t) != BROKER_BASE_SHA256:')
w('            print("had256_release: x-broker-drop is " + _sha(t)[:12] + ", not the 1.1.3 base " + BROKER_BASE_SHA256[:12] + "; applying by anchors")')
w('        for i, (old, new) in enumerate(HUNKS, 1):')
w('            n = t.count(old)')
w('            if n != 1:')
w('                raise SystemExit("had256_release: x-broker-drop hunk " + str(i) + " anchor is there " + str(n) + " times")')
w('            t = t.replace(old, new)')
w('        out = t')
w('    else:')
w('        raise SystemExit("had256_release: unknown rel " + rel)')
w('    return out.replace("\\n", "\\r\\n") if crlf else out')
w('')
w('')
w('if __name__ == "__main__":')
w('    b = apply("snippet:x-broker-drop", _code(_show(BASE, %r)))' % BD)
w('    assert _sha(b) == BROKER_NEW_SHA256, "x-broker-drop: base + 8 hunks != snapshot 3"')
w('    o = apply("snippet:x-owner-wizard", _code(_show(BASE, %r)))' % OW)
w('    assert _sha(o) == OWNER_LIVE_SHA256 and o.startswith(PRIVATE_PRELUDE) and _sha(o[len(PRIVATE_PRELUDE):]) == OWNER_NEW_SHA256')
w('    for v in ("A", "B"):')
w('        pg = _show(SNAPSHOT_PAGES, "docs/qa/had-256/page-4958/old.html").replace("\\r\\n", "\\n")')
w('        assert _sha(pg) == PAGE_OLD_SHA256')
w('        n = apply("page:4958:" + v, pg)')
w('        assert _sha(n) == PAGE_NEW_SHA256[v], v')
w('        try:')
w('            apply("page:4958:" + v, n)')
w('            raise AssertionError("page " + v + ": a second apply did not stop")')
w('        except SystemExit as e:')
w('            assert "already" in str(e), e')
w('    for rel, txt in (("snippet:x-broker-drop", b), ("snippet:x-owner-wizard", o)):')
w('        try:')
w('            apply(rel, txt)')
w('            raise AssertionError(rel + ": a second apply did not stop")')
w('        except SystemExit as e:')
w('            assert "already" in str(e), e')
w('    print("had256_release OK: x-broker-drop " + BROKER_BASE_SHA256[:12] + " -> " + BROKER_NEW_SHA256[:12] + " (8 hunks), snippet 707 " + OWNER_BASE_SHA256[:12] + " -> " + OWNER_LIVE_SHA256[:12] + " (prelude + " + OWNER_VERSION + " " + OWNER_NEW_SHA256[:12] + "); a second apply stops")')
io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
print('wrote', os.path.relpath(OUT, REPO), '| snap', SNAP, '| broker', BROKER_VERSION, sha(base_bd)[:12], '->', sha(snap_bd)[:12], '| owner', OWNER_VERSION, sha(base_ow)[:12], '->', sha(live_ow)[:12], '(code', sha(snap_ow)[:12] + ')')
