"""Builds docs/qa/had-256/RESULTS.md from docs/qa/had-256/results.json (every row a test recorded, with its label).
A row is PASS only if every AFTER check under it ran on real WordPress (label real-wp or real-wp+chrome) and passed.
"""
import json
import subprocess

from bench import RESULTS, QA, REPO

ROWS = {
    'L01': 'new / existing account, bad email, wrong password, retry; recovery and sign-in do not reveal an account',
    'L02': 'recovery, valid / expired / used token, back to the draft',
    'L03': 'two synthetic accounts and anonymous: no reading, changing or publishing of the other\'s draft, media or preview',
    'L04': 'typing, autosave, refresh, close and reopen: confirmed fields and photos kept, the save time is true',
    'L05': 'offline before a save and during a request; an answer lost after the commit',
    'L06': 'storage blocked or full, private browsing',
    'L07': 'two tabs on the same revision: no silent last-write-wins',
    'L08': 'two parallel publishes and a retry after a timeout or crash: one listing, a stable result',
    'L09': 'JPEG / PNG / WebP / HEIC, rotation, over 15 MB, fake type, corrupt file',
    'L10': 'a failed photo, add / remove during upload, refresh during upload',
    'L11': 'validation / 429 / 5xx / 401 / expired nonce / AI timeout',
    'L12': 'preview, then fix price / city / photo: the publish matches what was approved',
    'L13': 'pending / held, fix, publish; edit, sold, let, remove',
    'L14': '320-1440, he / en, keyboard: no overflow, nothing covered, focus, labels, 44 px, contrast',
    'L15': 'back / forward, recovery and back, accessibility and the WhatsApp bar',
    'L16': 'regression: snippets 707 / 699, auth, broker drop, property pages, payment stays off',
    'L17': 'rollback of code and snippet, data made by the new version kept',
}
NOT_RUN = {
    'L14': 'the phone keyboard (a real device) was not run: headless Chrome has no on-screen keyboard',
    'L09': 'a real HEIC photo was not decoded: no HEIC encoder or decoder on this machine, and the bench PHP (Imagick without HEIC) refuses HEIC by design',
    'L16': 'snippet 699 (the broker sign-up) and the broker /drop/<token>/ page were not exercised end to end on the bench; the shared engine they call (nl_drop_build) was',
    'L11': 'AI timeout: not applicable, the 2.0 journey makes no model call',
}


def main():
    rows = json.loads(RESULTS.read_text(encoding='utf-8'))
    after = [r for r in rows if r.get('variant') == 'after']
    before = [r for r in rows if r.get('variant') == 'before']
    head = subprocess.run(['git', '-C', str(REPO), 'rev-parse', '--short', 'HEAD'], capture_output=True, text=True).stdout.strip()
    out = ['# HAD-256 · results (generated by scripts/had-256/tests/make_report.py)', '',
           'Code under test: the working tree at HEAD `%s` (see README for the named snapshots). Labels: **real-wp** = the real modules inside WordPress Playground (SQLite) over HTTP; **real-wp+chrome** = the same, driven by a real Chrome; **mock** = a stub only (never counted as a pass). SQLite is not the live MySQL: see README.' % head, '',
           '| Row | Contract | AFTER | Checks (pass / all) | Label | Not run, and why |', '|---|---|---|---|---|---|']
    for k, title in ROWS.items():
        rs = [r for r in after if r['id'] == k]
        real = [r for r in rs if r.get('label', '').startswith('real')]
        npass = len([r for r in real if r['status'] == 'pass'])
        nfail = len([r for r in real if r['status'] == 'fail'])
        status = 'not run' if not real else ('PASS' if nfail == 0 else 'FAIL')
        if status == 'PASS' and k in NOT_RUN and k not in ('L11',):
            status = 'PASS (partial)'
        labels = ', '.join(sorted(set(r.get('label', '') for r in rs)))
        out.append('| %s | %s | %s | %d / %d | %s | %s |' % (k, title, status, npass, len(real), labels or '-', NOT_RUN.get(k, '')))
    out += ['', '## Every AFTER check', '']
    for r in sorted(after, key=lambda r: (r['id'], r['title'])):
        out.append('- **%s** [%s] %s · `%s` · %s' % (r['id'], r['status'].upper(), r['title'], r.get('label', ''), r.get('at', '')))
    out += ['', '## BEFORE (base code 6e9cf930 on :9411), the same pressure', '']
    for r in sorted(before, key=lambda r: (r['id'], r['title'])):
        ev = json.dumps(r.get('evidence', {}), ensure_ascii=False)
        out.append('- **%s** [%s] %s · `%s`  \n  %s' % (r['id'], r['status'].upper(), r['title'], r.get('label', ''), (ev[:600] + ('…' if len(ev) > 600 else ''))))
    other = [r for r in rows if r.get('variant') not in ('after', 'before')]
    (QA / 'RESULTS.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('written', QA / 'RESULTS.md', len(after), 'after rows', len(before), 'before rows')


if __name__ == '__main__':
    main()
