/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrbanRenewalRouteImport } from './routes/urban-renewal'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as MyRentalsRouteImport } from './routes/my-rentals'
import { Route as MyRenewalRouteImport } from './routes/my-renewal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as EnRouteImport } from './routes/en'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandoffIndexRouteImport } from './routes/handoff.index'
import { Route as ShowroomProjectIdRouteImport } from './routes/showroom.$projectId'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as HandoffShowroomRouteImport } from './routes/handoff.showroom'
import { Route as HandoffProjectsRouteImport } from './routes/handoff.projects'
import { Route as HandoffHomepageRouteImport } from './routes/handoff.homepage'
import { Route as HandoffCompareRouteImport } from './routes/handoff.compare'
import { Route as HandoffFileSplatRouteImport } from './routes/handoff-file.$'
import { Route as CitiesCityRouteImport } from './routes/cities.$city'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as HandoffDocSlugRouteImport } from './routes/handoff.doc.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const UrbanRenewalRoute = UrbanRenewalRouteImport.update({
  id: '/urban-renewal',
  path: '/urban-renewal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRentalsRoute = MyRentalsRouteImport.update({
  id: '/my-rentals',
  path: '/my-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRenewalRoute = MyRenewalRouteImport.update({
  id: '/my-renewal',
  path: '/my-renewal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffIndexRoute = HandoffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HandoffRoute,
} as any)
const ShowroomProjectIdRoute = ShowroomProjectIdRouteImport.update({
  id: '/showroom/$projectId',
  path: '/showroom/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffShowroomRoute = HandoffShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => HandoffRoute,
} as any)
const HandoffProjectsRoute = HandoffProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => HandoffRoute,
} as any)
const HandoffHomepageRoute = HandoffHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => HandoffRoute,
} as any)
const HandoffCompareRoute = HandoffCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => HandoffRoute,
} as any)
const HandoffFileSplatRoute = HandoffFileSplatRouteImport.update({
  id: '/handoff-file/$',
  path: '/handoff-file/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/cities/$city',
  path: '/cities/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandoffDocSlugRoute = HandoffDocSlugRouteImport.update({
  id: '/doc/$slug',
  path: '/doc/$slug',
  getParentRoute: () => HandoffRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/guides': typeof GuidesRoute
  '/handoff': typeof HandoffRouteWithChildren
  '/listings': typeof ListingsRoute
  '/mcp': typeof McpRoute
  '/my-renewal': typeof MyRenewalRoute
  '/my-rentals': typeof MyRentalsRoute
  '/professionals': typeof ProfessionalsRoute
  '/projects': typeof ProjectsRoute
  '/urban-renewal': typeof UrbanRenewalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cities/$city': typeof CitiesCityRoute
  '/handoff-file/$': typeof HandoffFileSplatRoute
  '/handoff/compare': typeof HandoffCompareRoute
  '/handoff/homepage': typeof HandoffHomepageRoute
  '/handoff/projects': typeof HandoffProjectsRoute
  '/handoff/showroom': typeof HandoffShowroomRoute
  '/listing/$id': typeof ListingIdRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/showroom/$projectId': typeof ShowroomProjectIdRoute
  '/handoff/': typeof HandoffIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/handoff/doc/$slug': typeof HandoffDocSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/guides': typeof GuidesRoute
  '/listings': typeof ListingsRoute
  '/mcp': typeof McpRoute
  '/my-renewal': typeof MyRenewalRoute
  '/my-rentals': typeof MyRentalsRoute
  '/professionals': typeof ProfessionalsRoute
  '/projects': typeof ProjectsRoute
  '/urban-renewal': typeof UrbanRenewalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cities/$city': typeof CitiesCityRoute
  '/handoff-file/$': typeof HandoffFileSplatRoute
  '/handoff/compare': typeof HandoffCompareRoute
  '/handoff/homepage': typeof HandoffHomepageRoute
  '/handoff/projects': typeof HandoffProjectsRoute
  '/handoff/showroom': typeof HandoffShowroomRoute
  '/listing/$id': typeof ListingIdRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/showroom/$projectId': typeof ShowroomProjectIdRoute
  '/handoff': typeof HandoffIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/handoff/doc/$slug': typeof HandoffDocSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/en': typeof EnRoute
  '/glossary': typeof GlossaryRoute
  '/guides': typeof GuidesRoute
  '/handoff': typeof HandoffRouteWithChildren
  '/listings': typeof ListingsRoute
  '/mcp': typeof McpRoute
  '/my-renewal': typeof MyRenewalRoute
  '/my-rentals': typeof MyRentalsRoute
  '/professionals': typeof ProfessionalsRoute
  '/projects': typeof ProjectsRoute
  '/urban-renewal': typeof UrbanRenewalRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/cities/$city': typeof CitiesCityRoute
  '/handoff-file/$': typeof HandoffFileSplatRoute
  '/handoff/compare': typeof HandoffCompareRoute
  '/handoff/homepage': typeof HandoffHomepageRoute
  '/handoff/projects': typeof HandoffProjectsRoute
  '/handoff/showroom': typeof HandoffShowroomRoute
  '/listing/$id': typeof ListingIdRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/showroom/$projectId': typeof ShowroomProjectIdRoute
  '/handoff/': typeof HandoffIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/handoff/doc/$slug': typeof HandoffDocSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/en'
    | '/glossary'
    | '/guides'
    | '/handoff'
    | '/listings'
    | '/mcp'
    | '/my-renewal'
    | '/my-rentals'
    | '/professionals'
    | '/projects'
    | '/urban-renewal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cities/$city'
    | '/handoff-file/$'
    | '/handoff/compare'
    | '/handoff/homepage'
    | '/handoff/projects'
    | '/handoff/showroom'
    | '/listing/$id'
    | '/project/$slug'
    | '/showroom/$projectId'
    | '/handoff/'
    | '/.mcp/invoke-tool/$tool'
    | '/handoff/doc/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/en'
    | '/glossary'
    | '/guides'
    | '/listings'
    | '/mcp'
    | '/my-renewal'
    | '/my-rentals'
    | '/professionals'
    | '/projects'
    | '/urban-renewal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cities/$city'
    | '/handoff-file/$'
    | '/handoff/compare'
    | '/handoff/homepage'
    | '/handoff/projects'
    | '/handoff/showroom'
    | '/listing/$id'
    | '/project/$slug'
    | '/showroom/$projectId'
    | '/handoff'
    | '/.mcp/invoke-tool/$tool'
    | '/handoff/doc/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/en'
    | '/glossary'
    | '/guides'
    | '/handoff'
    | '/listings'
    | '/mcp'
    | '/my-renewal'
    | '/my-rentals'
    | '/professionals'
    | '/projects'
    | '/urban-renewal'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/cities/$city'
    | '/handoff-file/$'
    | '/handoff/compare'
    | '/handoff/homepage'
    | '/handoff/projects'
    | '/handoff/showroom'
    | '/listing/$id'
    | '/project/$slug'
    | '/showroom/$projectId'
    | '/handoff/'
    | '/.mcp/invoke-tool/$tool'
    | '/handoff/doc/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ContactRoute: typeof ContactRoute
  EnRoute: typeof EnRoute
  GlossaryRoute: typeof GlossaryRoute
  GuidesRoute: typeof GuidesRoute
  HandoffRoute: typeof HandoffRouteWithChildren
  ListingsRoute: typeof ListingsRoute
  McpRoute: typeof McpRoute
  MyRenewalRoute: typeof MyRenewalRoute
  MyRentalsRoute: typeof MyRentalsRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ProjectsRoute: typeof ProjectsRoute
  UrbanRenewalRoute: typeof UrbanRenewalRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CitiesCityRoute: typeof CitiesCityRoute
  HandoffFileSplatRoute: typeof HandoffFileSplatRoute
  ListingIdRoute: typeof ListingIdRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  ShowroomProjectIdRoute: typeof ShowroomProjectIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urban-renewal': {
      id: '/urban-renewal'
      path: '/urban-renewal'
      fullPath: '/urban-renewal'
      preLoaderRoute: typeof UrbanRenewalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rentals': {
      id: '/my-rentals'
      path: '/my-rentals'
      fullPath: '/my-rentals'
      preLoaderRoute: typeof MyRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-renewal': {
      id: '/my-renewal'
      path: '/my-renewal'
      fullPath: '/my-renewal'
      preLoaderRoute: typeof MyRenewalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/': {
      id: '/handoff/'
      path: '/'
      fullPath: '/handoff/'
      preLoaderRoute: typeof HandoffIndexRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/showroom/$projectId': {
      id: '/showroom/$projectId'
      path: '/showroom/$projectId'
      fullPath: '/showroom/$projectId'
      preLoaderRoute: typeof ShowroomProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/showroom': {
      id: '/handoff/showroom'
      path: '/showroom'
      fullPath: '/handoff/showroom'
      preLoaderRoute: typeof HandoffShowroomRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/handoff/projects': {
      id: '/handoff/projects'
      path: '/projects'
      fullPath: '/handoff/projects'
      preLoaderRoute: typeof HandoffProjectsRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/handoff/homepage': {
      id: '/handoff/homepage'
      path: '/homepage'
      fullPath: '/handoff/homepage'
      preLoaderRoute: typeof HandoffHomepageRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/handoff/compare': {
      id: '/handoff/compare'
      path: '/compare'
      fullPath: '/handoff/compare'
      preLoaderRoute: typeof HandoffCompareRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/handoff-file/$': {
      id: '/handoff-file/$'
      path: '/handoff-file/$'
      fullPath: '/handoff-file/$'
      preLoaderRoute: typeof HandoffFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/cities/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/doc/$slug': {
      id: '/handoff/doc/$slug'
      path: '/doc/$slug'
      fullPath: '/handoff/doc/$slug'
      preLoaderRoute: typeof HandoffDocSlugRouteImport
      parentRoute: typeof HandoffRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HandoffRouteChildren {
  HandoffCompareRoute: typeof HandoffCompareRoute
  HandoffHomepageRoute: typeof HandoffHomepageRoute
  HandoffProjectsRoute: typeof HandoffProjectsRoute
  HandoffShowroomRoute: typeof HandoffShowroomRoute
  HandoffIndexRoute: typeof HandoffIndexRoute
  HandoffDocSlugRoute: typeof HandoffDocSlugRoute
}

const HandoffRouteChildren: HandoffRouteChildren = {
  HandoffCompareRoute: HandoffCompareRoute,
  HandoffHomepageRoute: HandoffHomepageRoute,
  HandoffProjectsRoute: HandoffProjectsRoute,
  HandoffShowroomRoute: HandoffShowroomRoute,
  HandoffIndexRoute: HandoffIndexRoute,
  HandoffDocSlugRoute: HandoffDocSlugRoute,
}

const HandoffRouteWithChildren =
  HandoffRoute._addFileChildren(HandoffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsRoute: CalculatorsRoute,
  ContactRoute: ContactRoute,
  EnRoute: EnRoute,
  GlossaryRoute: GlossaryRoute,
  GuidesRoute: GuidesRoute,
  HandoffRoute: HandoffRouteWithChildren,
  ListingsRoute: ListingsRoute,
  McpRoute: McpRoute,
  MyRenewalRoute: MyRenewalRoute,
  MyRentalsRoute: MyRentalsRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ProjectsRoute: ProjectsRoute,
  UrbanRenewalRoute: UrbanRenewalRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CitiesCityRoute: CitiesCityRoute,
  HandoffFileSplatRoute: HandoffFileSplatRoute,
  ListingIdRoute: ListingIdRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  ShowroomProjectIdRoute: ShowroomProjectIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

