#!/usr/bin/env python3
"""
NadLan repo inventory — the single index every agent reads FIRST.

Generates INVENTORY.md at the repo root: every GLB (with tris/dims so a good
model is never mistaken for junk and swung out), every project's data status,
key engine files, and the graveyard of deleted/scrapped assets.

Run after adding or removing any valuable asset:
    python3 scripts/build-inventory.py

GLBs are EXPENSIVE to compute — this inventory + docs/GRAVEYARD.md are the
guardrail: nothing valuable disappears silently.
"""
import os, glob, json, subprocess, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def rel(p): return os.path.relpath(p, ROOT)

def measure_glb(path):
    try:
        import trimesh
        s = trimesh.load(path)
        geoms = s.geometry.values() if hasattr(s, "geometry") else []
        tris = sum(g.faces.shape[0] for g in geoms)
        ext = [round(float(x), 1) for x in s.extents] if hasattr(s, "extents") else None
        return tris, ext
    except Exception:
        return None, None

def git_date(path):
    try:
        return subprocess.check_output(
            ["git", "-C", ROOT, "log", "-1", "--format=%cs", "--", path],
            stderr=subprocess.DEVNULL).decode().strip() or "?"
    except Exception:
        return "?"

def scan_glbs():
    rows = []
    for p in glob.glob(os.path.join(ROOT, "**", "*.glb"), recursive=True):
        if "/node_modules/" in p:
            continue
        sz = os.path.getsize(p)
        tris, ext = measure_glb(p)
        # "grounded?" heuristic: a huge flat ground plate = the dot-on-plate problem
        flag = ""
        if ext and ext[0] > 700 and ext[1] < ext[0] * 0.25:
            flag = "⚠ oversized ground plate (dot-on-plate)"
        elif tris and tris > 8000:
            flag = "★ rich"
        rows.append((rel(p), sz, tris, ext, flag, git_date(p)))
    rows.sort(key=lambda r: -(r[2] or 0))
    return rows

def scan_projects():
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "data/projects/*.json"))):
        b = os.path.basename(f)
        if b.startswith("_") or b == "index.json":
            continue
        d = json.load(open(f, encoding="utf-8"))
        idn = d.get("identity", {})
        loc = d.get("location", {})
        a3d = d.get("assets_3d", {}) or {}
        rows.append({
            "id": d["id"],
            "name": idn.get("name_he", ""),
            "developer": idn.get("developer", ""),
            "geocode": loc.get("geocode_status", ""),
            "model": (a3d.get("glb_model") or "").split("/")[-1] or "—",
            "ready": d.get("db_meta", {}).get("ready_for_page", False),
            "source": d.get("db_meta", {}).get("source_batch", ""),
        })
    return rows

def read_graveyard():
    gp = os.path.join(ROOT, "docs/GRAVEYARD.md")
    return open(gp, encoding="utf-8").read().strip() if os.path.exists(gp) else \
        "_(none logged yet — when you delete a valuable asset, add it here)_"

def main():
    today = os.environ.get("INVENTORY_DATE", "")  # deterministic in CI; else git
    if not today:
        try:
            today = subprocess.check_output(["git", "-C", ROOT, "log", "-1", "--format=%cs"]).decode().strip()
        except Exception:
            today = "unknown"
    glbs = scan_glbs()
    projs = scan_projects()
    total_glb_bytes = sum(r[1] for r in glbs)

    out = []
    out.append("# NadLan repo inventory\n")
    out.append("> **Read this first.** Auto-generated by `scripts/build-inventory.py`. "
               "The single index of valuable assets so no work is lost across sessions "
               "and no GLB is swung out. Regenerate after adding/removing assets. "
               "Deletions go in `docs/GRAVEYARD.md`.\n")
    out.append(f"_Last built (git date): {today} · {len(glbs)} GLBs "
               f"({total_glb_bytes//1024} KB) · {len(projs)} projects_\n")

    out.append("\n## 3D models (GLB) — expensive, never delete without logging\n")
    out.append("| model | tris | dims (m) | KB | note | added |\n|---|---:|---|---:|---|---|")
    for path, sz, tris, ext, flag, dt in glbs:
        out.append(f"| `{path}` | {tris if tris is not None else '?'} | "
                   f"{ext if ext else '?'} | {sz//1024} | {flag} | {dt} |")

    out.append("\n## Projects (canonical DB `data/projects/`)\n")
    out.append("| id | developer | model | geocode | ready | source |\n|---|---|---|---|:--:|---|")
    for p in projs:
        out.append(f"| `{p['id']}` | {p['developer'] or '—'} | {p['model']} | "
                   f"{p['geocode'] or '—'} | {'✅' if p['ready'] else '—'} | {p['source']} |")

    out.append("\n## Key engine / factory files\n")
    keys = [
        ("plugins/nadlan-config/assets/showroom-engine/engine.js", "selectable showroom (hotspots+facade+panels)"),
        ("plugins/nadlan-config/assets/showroom-engine/data.js", "showroom fallback project data"),
        ("plugins/nadlan-config/inc/showroom-engine.php", "engine mount + CMS wiring"),
        ("scripts/generate-massing.py", "materials→GLB massing factory"),
        ("handoff/claude-design/2026-07-03-project-page-factory/generate.py", "HTML project-page factory"),
        ("handoff/claude-design/2026-07-04-drone-map/israel-projects-drone-map.html", "Mapbox drone map"),
        ("data/projects/_schema.json", "project record schema"),
        ("handoff/research/prompts/full-world-enrichment.txt", "per-project data prompt"),
    ]
    out.append("| file | what it is | present |\n|---|---|:--:|")
    for f, desc in keys:
        out.append(f"| `{f}` | {desc} | {'✅' if os.path.exists(os.path.join(ROOT, f)) else '❌ MISSING'} |")

    out.append("\n## Graveyard (deleted / scrapped — do not resurrect blindly)\n")
    out.append(read_graveyard())
    out.append("")

    with open(os.path.join(ROOT, "INVENTORY.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"INVENTORY.md written: {len(glbs)} GLBs, {len(projs)} projects")

if __name__ == "__main__":
    main()
