#!/usr/bin/env bash
# rebuild-master-skill.sh — regenerates skills/MASTER-SKILL.md by importing
# every skill from every known location. Individual skills stay alive; this
# is the index every agent reads first.
# Run after adding any new skill anywhere in the repo.

set -e
cd "$(dirname "$0")/.." 2>/dev/null

OUT=skills/MASTER-SKILL.md
: > "$OUT"

cat >> "$OUT" <<'HEADER'
# MASTER-SKILL.md — every skill in the repo, in one file

> **Read this file every session, before any work.**
> This file is auto-generated by `scripts/rebuild-master-skill.sh` from every skill in the repo.
> **Individual skill files stay alive** — this is the index, not a replacement.
> Update an individual skill, then run: `bash scripts/rebuild-master-skill.sh`

---

## How to use this file

1. Read the **rules** section first (mistakes, discipline, sync).
2. Read the **product** section (Lovable design rules, showroom rules, language rules).
3. For deep-dive, follow the `→` link to the individual skill file.
4. If you just need fast onboarding, the headline of each `### skill:` line is enough.

---

HEADER

emit_section() {
  local title="$1"
  shift
  local files=("$@")
  [ ${#files[@]} -eq 0 ] && return
  echo "## $title" >> "$OUT"
  echo "" >> "$OUT"
  for f in "${files[@]}"; do
    [ -f "$f" ] || continue
    # extract first H1 or filename as title
    local name
    name=$(grep -m1 -E '^# ' "$f" 2>/dev/null | sed 's/^# *//' || echo "$(basename "$f" .md)")
    echo "### skill: $name" >> "$OUT"
    echo "**→ $f**" >> "$OUT"
    echo "" >> "$OUT"
    # include the full content (so this file is a single source of truth)
    awk 'NR==1 && /^# /{next} {print}' "$f" >> "$OUT"
    echo "" >> "$OUT"
    echo "---" >> "$OUT"
    echo "" >> "$OUT"
  done
}

# RULES (discipline + coordination + autonomy + sync) come FIRST
RULES=()
for f in \
  skills/skill-release-discipline-and-mistakes.md \
  skills/agent-autonomy-playbook.md \
  COORDINATION.md \
  handoff/shared-knowledge/skills/nadlan-cross-agent-sync.md \
  ; do
  [ -f "$f" ] && RULES+=("$f")
done
emit_section "1. RULES — discipline, sync, autonomy (READ FIRST)" "${RULES[@]}"

# PRODUCT (Lovable design + showroom + language + listings)
PRODUCT=()
for f in handoff/shared-knowledge/skills/*.md; do
  [ -f "$f" ] && PRODUCT+=("$f")
done
emit_section "2. PRODUCT — Lovable design system + WordPress showroom rules" "${PRODUCT[@]}"

# LOVABLE REPORTS (strategy + redesign + brand)
LOVABLE=()
for f in handoff/lovable/*/reports/*.md; do
  [ -f "$f" ] && LOVABLE+=("$f")
done
emit_section "3. LOVABLE REPORTS — strategy, showroom redesign, brand, prototype notes" "${LOVABLE[@]}"

# OTHER SKILLS in skills/ (everything else, alphabetized)
OTHER=()
while IFS= read -r f; do
  case "$f" in
    skills/skill-release-discipline-and-mistakes.md|skills/agent-autonomy-playbook.md|skills/MASTER-SKILL.md) ;;
    *) [ -f "$f" ] && OTHER+=("$f") ;;
  esac
done < <(find skills -maxdepth 1 -name '*.md' | sort)
emit_section "4. OTHER SKILLS — repo skills/ folder" "${OTHER[@]}"

# CLAUDE MISSION READOUT (if present)
if [ -f handoff/claude/2026-06-23-mission-readout.md ]; then
  emit_section "5. CLAUDE MISSION READOUT" handoff/claude/2026-06-23-mission-readout.md
fi

echo "rebuilt $OUT — $(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes"
